from __future__ import annotations

LONG_DIP_ENTRY_EARLY_DIP_MAX_SECONDS = 10
LONG_DIP_ENTRY_EARLY_DIP_MIN_PCT = -1.0
LONG_DIP_ENTRY_OPEN30_VOLUME_MIN = 0.0
LONG_DIP_ENTRY_RECLAIM_MAX_SECONDS = 30

LONG_DIP_TOP_N = 5
LONG_DIP_MIN_GAP_PCT = 0.0
LONG_DIP_MAX_GAP_PCT = 40.0
LONG_DIP_MIN_PREVIOUS_CLOSE = 0.0
LONG_DIP_MIN_PREMARKET_DOLLAR_VOLUME = 0.0
LONG_DIP_MIN_PREMARKET_VOLUME = 0
LONG_DIP_MIN_PREMARKET_TRADE_COUNT = 0
LONG_DIP_SPARSE_MIN_PREMARKET_ACTIVE_SECONDS = 30
LONG_DIP_EARLY_MIN_PREMARKET_ACTIVE_SECONDS = 45
LONG_DIP_BUILDING_MIN_PREMARKET_ACTIVE_SECONDS = 60
LONG_DIP_MIN_PREMARKET_ACTIVE_SECONDS = 90
LONG_DIP_POSITION_BUDGET_USD = 10_000.0

LONG_DIP_DEFAULTS = {
    "top_n": LONG_DIP_TOP_N,
    "min_gap_pct": LONG_DIP_MIN_GAP_PCT,
    "max_gap_pct": LONG_DIP_MAX_GAP_PCT,
    "min_previous_close": LONG_DIP_MIN_PREVIOUS_CLOSE,
    "min_premarket_dollar_volume": LONG_DIP_MIN_PREMARKET_DOLLAR_VOLUME,
    "min_premarket_volume": LONG_DIP_MIN_PREMARKET_VOLUME,
    "min_premarket_trade_count": LONG_DIP_MIN_PREMARKET_TRADE_COUNT,
    "min_premarket_active_seconds": LONG_DIP_MIN_PREMARKET_ACTIVE_SECONDS,
    "position_budget_usd": LONG_DIP_POSITION_BUDGET_USD,
}