from __future__ import annotations

LONG_DIP_ENTRY_EARLY_DIP_MAX_SECONDS = 10
LONG_DIP_ENTRY_EARLY_DIP_MIN_PCT = -1.0
LONG_DIP_ENTRY_OPEN30_VOLUME_MIN = 0.0
LONG_DIP_ENTRY_RECLAIM_MAX_SECONDS = 30
LONG_DIP_MIN_GAP_PCT = 0.0
LONG_DIP_MIN_PREMARKET_DOLLAR_VOLUME = 0.0

LONG_DIP_DEFAULTS = {
    "top_n": 5,
}