"""The partner one-pager cannot drift from the taxonomy it describes.

Weekly commercial review 2026-08-16 (P2): the page is generated from the
product cut manifest and the family claim record. This test regenerates it
on every run — a taxonomy change (tier membership, companion count) or a
claim change (family status) that forgets the page goes red here instead of
shipping a stale sheet to a design partner.
"""

from __future__ import annotations

from pathlib import Path

from scripts.generate_partner_surface_one_pager import (
    OUTPUT_PATH,
    STATUS,
    build_one_pager,
)

ROOT = Path(__file__).resolve().parents[1]


def test_the_committed_page_is_current() -> None:
    assert OUTPUT_PATH.read_text(encoding="utf-8") == build_one_pager()


def test_the_page_reflects_the_taxonomy_and_claims() -> None:
    page = build_one_pager()

    assert "SMC Long-Dip Suite" in page
    assert "GENERATED by scripts/generate_partner_surface_one_pager.py" in page
    # The FVG decision (2026-08-16) must be visible, not implied away.
    assert "In incubation (measured, not claimed): FVG" in page
    assert "BOS, OB, SWEEP" in page
    # No performance claim vocabulary on a partner-facing sheet.
    for forbidden in ("Sharpe", "win rate", "profitable", "edge is proven"):
        assert forbidden not in page, forbidden


def test_the_draft_banner_tracks_the_status_constant() -> None:
    page = build_one_pager()

    if STATUS == "draft_pending_operator_review":
        assert "DRAFT — operator content review pending" in page
    else:
        assert "DRAFT" not in page
