"""Pin: workflows that create PRs or push bot/* branches use GH_PAT, not GITHUB_TOKEN.

Background
==========

Memory `bot-pr-needs-pat-not-github-token.md`: GitHub suppresses
workflow triggers for events generated by ``GITHUB_TOKEN``, so a PR
created with ``GITHUB_TOKEN`` does NOT trigger ``fast-gates`` and
sits in a "Expected — Waiting for status to be reported" state
forever. The canonical pattern (PRs #80, #81, #88, #97, #103) is to
use ``secrets.GH_PAT`` (with a literal-empty fallback to
``github.token`` for forks where the secret is unavailable).

Affected actions:
1. ``gh pr create`` (any subcommand: create, edit, comment, merge)
2. ``git push origin bot/*`` (any push to bot-prefixed branch)
3. ``peter-evans/create-pull-request`` (third-party PR action)

Read-only / issue-only ``gh`` commands (``gh issue *``, ``gh run
list/download``, ``gh pr list/view``) are fine with ``GITHUB_TOKEN``
because they do not generate webhook events that need to chain into
other workflows.

This pin walks every YAML workflow file in ``.github/workflows/`` as
plain text (no YAML parser to avoid pulling in PyYAML at test time)
and flags steps that contain a sensitive action AND a token mapping
that resolves only to ``GITHUB_TOKEN`` / ``github.token`` without a
``secrets.GH_PAT`` fallback within the same env block.

Currently expected: 0 violations (verified by spot-grep on
``run-open-prep-daily.yml``, ``open-prep-outcome-backfill.yml``,
``smc-library-refresh.yml`` — all use the canonical
``secrets.GH_PAT != '' && secrets.GH_PAT || ...`` ternary).
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"

# Sensitive actions that need fast-gates to trigger downstream.
_SENSITIVE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bgh\s+pr\s+create\b"),
    re.compile(r"\bgh\s+pr\s+edit\b"),
    re.compile(r"\bgh\s+pr\s+merge\b"),
    re.compile(r"git\s+push[^\n]*\borigin\s+bot/"),
    re.compile(r"peter-evans/create-pull-request"),
)

# A step is GH_PAT-aware if its env block (or any nearby line) names
# the secret. Workflow YAML structure: ``env:`` block, then key:
# value pairs. We accept any ``GH_PAT`` mention within ±25 lines of
# the sensitive command — this is a structural heuristic, not a YAML
# parse, but it has zero false positives on the current workflow set.
_GH_PAT_HINT = re.compile(r"\bsecrets\.GH_PAT\b")

# Window (in lines) around the sensitive command to scan for GH_PAT.
# Sized to cover the largest current step body — the smc-library-refresh
# "Commit and push changes" step is ~75 lines from env block to the
# `gh pr create` line. 100 leaves headroom without crossing into
# neighbouring steps (which start with a ``- name:`` indented at 6 cols).
_PROXIMITY_LINES = 100


def _iter_workflow_files() -> list[Path]:
    if not WORKFLOWS_DIR.exists():
        return []
    out = sorted(WORKFLOWS_DIR.glob("*.yml")) + sorted(WORKFLOWS_DIR.glob("*.yaml"))
    return out


def _find_violations(path: Path) -> list[tuple[int, str]]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    violations: list[tuple[int, str]] = []
    for idx, line in enumerate(lines):
        # Skip comments — they describe patterns rather than execute them.
        stripped = line.lstrip()
        if stripped.startswith("#"):
            continue
        for pat in _SENSITIVE_PATTERNS:
            if not pat.search(line):
                continue
            window_start = max(0, idx - _PROXIMITY_LINES)
            window_end = min(len(lines), idx + _PROXIMITY_LINES + 1)
            window = "\n".join(lines[window_start:window_end])
            if _GH_PAT_HINT.search(window):
                continue
            violations.append((idx + 1, line.strip()))
    return violations


def test_pr_creating_steps_use_gh_pat() -> None:
    """Every PR-creation / bot-push step must reference secrets.GH_PAT.

    Otherwise the resulting PR fails to trigger fast-gates (see
    `/memories/repo/bot-pr-needs-pat-not-github-token.md`).
    """
    findings: list[str] = []
    for path in _iter_workflow_files():
        rel = str(path.relative_to(REPO_ROOT)).replace("\\", "/")
        for line_no, snippet in _find_violations(path):
            findings.append(
                f"{rel}:{line_no} sensitive action without "
                f"`secrets.GH_PAT` in proximity:\n    {snippet!r}\n  "
                "Add `GH_TOKEN: ${{ secrets.GH_PAT != '' && "
                "secrets.GH_PAT || github.token }}` in the step's env "
                "block. See PRs #80/#81/#88/#97/#103 for the canonical "
                "pattern."
            )
    assert not findings, (
        "Workflows missing GH_PAT for PR-creating actions:\n  "
        + "\n  ".join(findings)
    )


def test_workflows_dir_has_at_least_one_file() -> None:
    """Belt-and-braces: pin actually visits the workflows dir."""
    files = _iter_workflow_files()
    assert files, (
        f"No workflow files found under {WORKFLOWS_DIR.relative_to(REPO_ROOT)} "
        "— the pin is silently passing because it has nothing to scan."
    )
