"""Pin: workflows that create PRs or push bot/* branches use GH_PAT, not GITHUB_TOKEN.

Background
==========

Memory `bot-pr-needs-pat-not-github-token.md`: GitHub suppresses
workflow triggers for events generated by ``GITHUB_TOKEN``, so a PR
created with ``GITHUB_TOKEN`` does NOT trigger ``fast-gates`` and
sits in a "Expected — Waiting for status to be reported" state
forever. The canonical pattern (PRs #80, #81, #88, #97, #103) is to
use ``secrets.GH_PAT`` (with a literal-empty fallback to
``github.token`` for forks where the secret is unavailable).

Affected actions:
1. ``gh pr create`` (any subcommand: create, edit, comment, merge)
2. ``git push origin bot/*`` (any push to bot-prefixed branch)
3. ``peter-evans/create-pull-request`` (third-party PR action)

Read-only / issue-only ``gh`` commands (``gh issue *``, ``gh run
list/download``, ``gh pr list/view``) are fine with ``GITHUB_TOKEN``
because they do not generate webhook events that need to chain into
other workflows.

This pin walks every YAML workflow file in ``.github/workflows/`` as
plain text (no YAML parser to avoid pulling in PyYAML at test time)
and flags steps that contain a sensitive action AND a token mapping
that resolves only to ``GITHUB_TOKEN`` / ``github.token`` without a
``secrets.GH_PAT`` fallback within the same env block.

Currently expected: 0 violations (verified by spot-grep on
``run-open-prep-daily.yml``, ``open-prep-outcome-backfill.yml``,
``smc-library-refresh.yml`` — all use the canonical
``secrets.GH_PAT != '' && secrets.GH_PAT || ...`` ternary).
"""

from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS_DIR = REPO_ROOT / ".github" / "workflows"

# Workflows that are allowed to push to bot/* branches using github.token
# with job-level contents:write instead of secrets.GH_PAT. Each entry must
# cite the ADR/PR that explicitly approved the migration.
_GITHUB_TOKEN_BOT_PUSH_ALLOWLIST: frozenset[str] = frozenset({
    # PR #2956 (2026-06-26): the rolling benchmark only publishes a rolling
    # cache cursor (bot/live-experiment-snapshot) consumed by the live-overlay
    # daemon via the GitHub Contents API. No downstream workflow is triggered
    # by this push, so the GITHUB_TOKEN suppression rule does not apply. The
    # job explicitly elevates to contents: write and actions: read.
    "smc-measurement-benchmark-rolling.yml",
})

# Sensitive actions that need fast-gates to trigger downstream.
_SENSITIVE_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ``gh pr <create|edit|comment|merge>`` — any PR-mutating subcommand.
    re.compile(r"\bgh\s+pr\s+(?:create|edit|comment|merge)\b"),
    # Literal ``bot/...`` push (optionally quoted).
    re.compile(r"git\s+push[^\n]*\borigin\s+['\"]?bot/"),
    # Push to a fully-qualified refs/heads/bot/* ref (e.g.
    # ``git push --force-with-lease=refs/heads/bot/... "HEAD:refs/heads/bot/..."``).
    re.compile(r"git\s+push[^\n]*\brefs/heads/bot/"),
    # Variable push: ``git push origin "$BRANCH"`` / ``${BRANCH}``.
    re.compile(
        r"git\s+push[^\n]*\borigin\s+['\"]?\$"
        r"(?:\{[A-Za-z_][A-Za-z0-9_]*\}|[A-Za-z_][A-Za-z0-9_]*)"
    ),
    # Shell assignment of a ``bot/...`` ref (e.g.
    # ``BRANCH="bot/library-refresh-${GITHUB_RUN_ID}"``).
    re.compile(r"\b[A-Za-z_][A-Za-z0-9_]*=['\"]bot/"),
    re.compile(r"peter-evans/create-pull-request"),
)

# A step is GH_PAT-aware if its env block (or any nearby line) names
# the secret. Workflow YAML structure: ``env:`` block, then key:
# value pairs. We accept any ``GH_PAT`` mention within ±25 lines of
# the sensitive command — this is a structural heuristic, not a YAML
# parse, but it has zero false positives on the current workflow set.
_GH_PAT_HINT = re.compile(r"\bsecrets\.GH_PAT\b")
# A step is GH_PAT-aware only if it *binds* the secret to
# GH_TOKEN/GITHUB_TOKEN via the canonical ternary fallback. A bare
# mention in a comment or unrelated env var is not enough.
_GH_PAT_BINDING = re.compile(
    r"\b(?:GH_TOKEN|GITHUB_TOKEN)\s*:\s*[^\n]*\bsecrets\.GH_PAT\b"
)

# Binding that uses the repository-scoped GITHUB_TOKEN / github.token.
# Allowed only for workflows in _GITHUB_TOKEN_BOT_PUSH_ALLOWLIST that
# push cache-cursor bot/* branches where no downstream workflow must be
# triggered.
_GITHUB_TOKEN_BINDING = re.compile(
    r"\b(?:GH_TOKEN|GITHUB_TOKEN)\s*:\s*[^\n]*\$\{\{\s*github\.token\s*\}\}"
)

# Step boundary inside a workflow YAML: a list-item starting a new
# step (``- name:`` at any indentation). Used to bound the proximity
# scan to the enclosing step so a neighbouring step's GH_PAT mention
# can't satisfy the pin for an unrelated step.
_STEP_BOUNDARY = re.compile(r"^\s*-\s+name:\s")


def _iter_workflow_files() -> list[Path]:
    if not WORKFLOWS_DIR.exists():
        return []
    out = sorted(WORKFLOWS_DIR.glob("*.yml")) + sorted(WORKFLOWS_DIR.glob("*.yaml"))
    return out


def _step_bounds(lines: list[str], idx: int) -> tuple[int, int]:
    """Return the half-open ``(start, end)`` range of the step
    enclosing ``lines[idx]``. Walks backward to the nearest ``- name:``
    (or BOF) and forward to the next ``- name:`` (or EOF)."""
    start = 0
    for j in range(idx, -1, -1):
        if _STEP_BOUNDARY.match(lines[j]):
            start = j
            break
    end = len(lines)
    for j in range(idx + 1, len(lines)):
        if _STEP_BOUNDARY.match(lines[j]):
            end = j
            break
    return start, end


def _strip_comments(lines: list[str]) -> list[str]:
    """Return ``lines`` with comment-only lines removed so a rationale
    comment cannot satisfy the pin."""
    return [ln for ln in lines if not ln.lstrip().startswith("#")]


def _is_bot_push_pattern(pat: re.Pattern[str], line: str) -> bool:
    """Return True if the matched pattern is a bot/* push of any form."""
    return "bot/" in line and bool(re.search(r"git\s+push", line))


def _find_violations(path: Path) -> list[tuple[int, str]]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    allowed_github_token = path.name in _GITHUB_TOKEN_BOT_PUSH_ALLOWLIST
    violations: list[tuple[int, str]] = []
    for idx, line in enumerate(lines):
        # Skip comment-only lines — they describe patterns rather than
        # execute them.
        if line.lstrip().startswith("#"):
            continue
        for pat in _SENSITIVE_PATTERNS:
            if not pat.search(line):
                continue
            # Bound the scan to the enclosing step (between two
            # ``- name:`` markers) and strip comment-only lines so a
            # nearby rationale comment mentioning ``secrets.GH_PAT``
            # cannot satisfy the pin.
            step_start, step_end = _step_bounds(lines, idx)
            step_exec = "\n".join(_strip_comments(lines[step_start:step_end]))

            # Allowlisted bot/* cache-cursor pushes may use github.token
            # with explicit job-level contents:write.
            if (
                allowed_github_token
                and _is_bot_push_pattern(pat, line)
                and _GITHUB_TOKEN_BINDING.search(step_exec)
            ):
                continue

            # Require BOTH a mention of the secret AND an actual
            # binding to GH_TOKEN / GITHUB_TOKEN via the canonical ternary
            # fallback. The mention check catches obvious absences;
            # the binding check rules out cases where the secret is
            # referenced for an unrelated purpose.
            if _GH_PAT_HINT.search(step_exec) and _GH_PAT_BINDING.search(step_exec):
                continue
            violations.append((idx + 1, line.strip()))
    return violations


def test_pr_creating_steps_use_gh_pat() -> None:
    """Every PR-creation / bot-push step must reference secrets.GH_PAT
    (or be explicitly allowlisted to use github.token for a bot/*
    cache-cursor push where no downstream workflow trigger is needed).

    Otherwise the resulting PR fails to trigger fast-gates (see
    `/memories/repo/bot-pr-needs-pat-not-github-token.md`).
    """
    findings: list[str] = []
    for path in _iter_workflow_files():
        rel = str(path.relative_to(REPO_ROOT)).replace("\\", "/")
        for line_no, snippet in _find_violations(path):
            findings.append(
                f"{rel}:{line_no} sensitive action without "
                f"`secrets.GH_PAT` in proximity:\n    {snippet!r}\n  "
                "Add `GH_TOKEN: ${{ secrets.GH_PAT != '' && "
                "secrets.GH_PAT || github.token }}` in the step's env "
                "block. If this is an allowlisted bot/* cache-cursor "
                "push using github.token with job-level contents:write, "
                "add the workflow to `_GITHUB_TOKEN_BOT_PUSH_ALLOWLIST` "
                "and cite the approving PR/ADR. See PRs #80/#81/#88/#97/#103 "
                "for the canonical pattern."
            )
    assert not findings, (
        "Workflows missing GH_PAT for PR-creating actions:\n  "
        + "\n  ".join(findings)
    )


def test_workflows_dir_has_at_least_one_file() -> None:
    """Belt-and-braces: pin actually visits the workflows dir."""
    files = _iter_workflow_files()
    assert files, (
        f"No workflow files found under {WORKFLOWS_DIR.relative_to(REPO_ROOT)} "
        "— the pin is silently passing because it has nothing to scan."
    )
