import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  verifyPanelPublishContract,
  type PanelContractInput,
} from "../../../scripts/tv_publish_openprep_panel.js";

const SCRIPT_NAME = "Open-Prep Daily Panel";

const VALID_PANEL_TEXT = [
  "//@version=6",
  "// AUTOGENERATED by scripts/generate_openprep_pine_panel.py — DO NOT EDIT BY HAND.",
  `indicator("${SCRIPT_NAME}", overlay = true)`,
  "",
  'var string PANEL_WEATHER = "GREEN"',
  "",
].join("\n");

function writeFixture(panelText: string | null): PanelContractInput {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "tv-openprep-panel-contract-"));
  const pineDir = path.join(dir, "pine", "generated");
  fs.mkdirSync(pineDir, { recursive: true });
  const panelPath = path.join(pineDir, "openprep_daily_panel.pine");
  if (panelText !== null) {
    fs.writeFileSync(panelPath, panelText, "utf-8");
  }
  return { panel: panelPath, scriptName: SCRIPT_NAME };
}

test("verifyPanelPublishContract accepts a valid indicator panel", () => {
  const input = writeFixture(VALID_PANEL_TEXT);
  const details = verifyPanelPublishContract(input);
  assert.equal(details.scriptName, SCRIPT_NAME);
  assert.equal(details.panelPath, input.panel);
});

test("verifyPanelPublishContract rejects a missing source file", () => {
  const input = writeFixture(null);
  assert.throws(() => verifyPanelPublishContract(input), /Missing Open-Prep panel source/);
});

test("verifyPanelPublishContract rejects a wrong indicator header", () => {
  const input = writeFixture(VALID_PANEL_TEXT.replace(SCRIPT_NAME, "Something Else"));
  assert.throws(() => verifyPanelPublishContract(input), /header mismatch/);
});

test("verifyPanelPublishContract rejects a library() header (must be an indicator)", () => {
  const libText = VALID_PANEL_TEXT.replace(
    `indicator("${SCRIPT_NAME}", overlay = true)`,
    `library("${SCRIPT_NAME}")`,
  );
  assert.throws(() => verifyPanelPublishContract(writeFixture(libText)), /header mismatch/);
});

test("verifyPanelPublishContract rejects a missing version directive", () => {
  const noVersion = VALID_PANEL_TEXT.replace("//@version=6\n", "");
  assert.throws(() => verifyPanelPublishContract(writeFixture(noVersion)), /@version=6/);
});
