#!/usr/bin/env bash
# C13 Phase-A — daily local cron driver to push audit artefacts to the
# dedicated `data/phase-a-audit` branch (keeps cron-bot churn off main).
#
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.audit-push.plist
# on Mon-Fri @ 17:30 local time (one hour after US-equity close).
#
# Repo policy: never --force, never --no-verify. Branch is protected on
# the remote; pushes use the same PAT-authenticated origin as the local
# `git push` (gh CLI keyring credentials are reused by git).

set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
DATE="$(date -u +%Y-%m-%d)"

cd "${REPO}"

AUDIT="cache/live/incubation_${DATE}.jsonl"
SETUPS="cache/live/setups_${DATE}.jsonl"
GATES="cache/live/gate_status.json"

if [[ ! -f "${AUDIT}" ]]; then
    echo "no audit artefact at ${AUDIT}; skipping push"
    exit 0
fi

# Ensure we're on data/phase-a-audit and that it tracks origin.
ORIG_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
trap 'git checkout "${ORIG_BRANCH}" 2>/dev/null || true' EXIT

git fetch origin data/phase-a-audit --quiet
git checkout data/phase-a-audit 2>/dev/null || \
    git checkout -b data/phase-a-audit origin/data/phase-a-audit

# Pull latest in case yesterday's run already pushed.
git pull --ff-only origin data/phase-a-audit || true

git add "${AUDIT}" "${SETUPS}" "${GATES}" 2>/dev/null || true

if git diff --staged --quiet; then
    echo "no audit changes to commit"
    exit 0
fi

git -c user.name="skippalgo-c13-cron" \
    -c user.email="c13-cron@skippalgo.io" \
    commit -m "chore(c13): phase-a audit ${DATE}" \
           -m "Generated by com.skippalgo.c13.audit-push launchd agent."

git push origin data/phase-a-audit || \
    echo "push to data/phase-a-audit failed (non-fatal); will retry tomorrow"
