#!/usr/bin/env bash
# C13 / T8.2 — daily local cron driver for opening-imbalance collection.
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.collect-imbalance.plist
# on Mon-Fri @ 09:28 local time. Idempotent on the artefact path.

set -euo pipefail

# Derive REPO from this script's location so the driver is portable across
# workstations without editing the tracked file. VENV / WATCHLIST can be
# overridden via environment variables (set in the LaunchAgent plist's
# ``EnvironmentVariables`` block) for non-default paths.
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${C13_VENV:-${HOME}/.venv}"
WATCHLIST="${C13_WATCHLIST:-${REPO}/reports/databento_watchlist_top5_pre1530.csv}"

DATE="$(date -u +%Y-%m-%d)"
OUTPUT="${REPO}/cache/imbalance/${DATE}.jsonl"
SUMMARY="${REPO}/cache/imbalance/${DATE}.summary.json"

cd "${REPO}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"

mkdir -p "${REPO}/cache/imbalance"

python -m scripts.collect_opening_imbalances \
    --watchlist "${WATCHLIST}" \
    --output    "${OUTPUT}" \
    --summary-output "${SUMMARY}" \
    --trade-date "${DATE}"

# Best-effort commit + push so the GH-hosted cron sees the artefact.
# Repo policy: never --force, never --no-verify.
git add "cache/imbalance/${DATE}.jsonl" "cache/imbalance/${DATE}.summary.json" || true
if ! git diff --staged --quiet; then
    # Lane 7 (provider-boundary audit, 2026-04-27): ``git push origin
    # HEAD`` would push the imbalance artefact onto whatever branch
    # the developer had checked out when the LaunchAgent fired —
    # silently polluting feature branches with cron data. Only
    # commit+push when HEAD is on a designated data branch.
    CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
    case "${CURRENT_BRANCH}" in
        main|data/*)
            git commit -m "chore(c13): imbalance snapshot ${DATE}" -m "Generated by com.skippalgo.c13.collect-imbalance launchd agent."
            git push origin "${CURRENT_BRANCH}" || echo "git push failed (non-fatal); will retry tomorrow"
            ;;
        *)
            echo "imbalance cron: HEAD on '${CURRENT_BRANCH}' (not main or data/*); leaving artefact uncommitted to avoid polluting a feature branch" >&2
            git reset HEAD -- "cache/imbalance/${DATE}.jsonl" "cache/imbalance/${DATE}.summary.json" >/dev/null 2>&1 || true
            ;;
    esac
fi
