#!/usr/bin/env bash
# C13 / Phase-A — daily audit-log push driver.
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.phase-a-audit-push.plist
# on Mon-Fri @ 17:30 local time (ET). Commits today's Phase-A inputs +
# audit log to the protected ``data/phase-a-audit`` branch on origin so
# the unattended GH-cron consumes them.
#
# Repo policy: never --force, never --no-verify. If the working tree
# is clean (no Phase-A activity today, e.g. holiday), this is a no-op.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
AUDIT_BRANCH="${C13_AUDIT_BRANCH:-data/phase-a-audit}"

DATE="$(date -u +%Y-%m-%d)"
PHASE_A_DIR_REL="cache/phase_a"
INCUBATION_DIR_REL="cache/incubation"

cd "${REPO}"

# Stash any unrelated working-tree changes so we never accidentally
# push them to the audit branch. If nothing to stash, this is a no-op.
STASHED=0
if ! git diff --quiet || ! git diff --staged --quiet; then
    git stash push --include-untracked -m "c13-audit-push-autostash-${DATE}" || true
    STASHED=1
fi

ORIG_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

cleanup() {
    git checkout "${ORIG_BRANCH}" >/dev/null 2>&1 || true
    if [[ "${STASHED}" -eq 1 ]]; then
        git stash pop >/dev/null 2>&1 || true
    fi
}
trap cleanup EXIT

# Make sure we have the latest audit branch from origin, then check it
# out (creating the local tracking branch if it doesn't exist yet).
git fetch origin "${AUDIT_BRANCH}" || true
if git show-ref --verify --quiet "refs/heads/${AUDIT_BRANCH}"; then
    git checkout "${AUDIT_BRANCH}"
    git merge --ff-only "origin/${AUDIT_BRANCH}" || true
else
    git checkout -B "${AUDIT_BRANCH}" "origin/${AUDIT_BRANCH}"
fi

ADDED=0
for rel in \
    "${PHASE_A_DIR_REL}/setups_${DATE}.jsonl" \
    "${PHASE_A_DIR_REL}/setups_${DATE}.meta.json" \
    "${PHASE_A_DIR_REL}/gate_status_${DATE}.json" \
    "${INCUBATION_DIR_REL}/incubation_${DATE}.jsonl"
do
    if [[ -f "${REPO}/${rel}" ]]; then
        git add "${rel}" || true
        ADDED=1
    fi
done

if [[ "${ADDED}" -eq 0 ]]; then
    echo "No Phase-A artefacts found for ${DATE}; nothing to push."
    exit 0
fi

if git diff --staged --quiet; then
    echo "Phase-A artefacts unchanged for ${DATE}; nothing to push."
    exit 0
fi

git commit -m "chore(c13): phase-a audit ${DATE}" \
           -m "Generated by com.skippalgo.c13.phase-a-audit-push launchd agent."

if ! git push origin "${AUDIT_BRANCH}"; then
    echo "git push failed (non-fatal); will retry tomorrow." >&2
    exit 0
fi

echo "Phase-A audit pushed for ${DATE} to ${AUDIT_BRANCH}."
