#!/usr/bin/env bash
# C13 / T7.1 — daily local cron driver for WSH earnings calendar pull.
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.wsh-earnings.plist
# on Mon-Fri @ 16:30 local time. Idempotent on the artefact path.

set -euo pipefail

# Derive REPO from this script's location so the driver is portable across
# workstations without editing the tracked file. VENV / WATCHLIST can be
# overridden via environment variables (set in the LaunchAgent plist's
# ``EnvironmentVariables`` block).
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${C13_VENV:-${HOME}/.venv}"
WATCHLIST="${C13_WATCHLIST:-${REPO}/reports/databento_watchlist_top5_pre1530.csv}"
WINDOW_DAYS=14

DATE="$(date -u +%Y-%m-%d)"
OUTPUT="${REPO}/cache/wsh/${DATE}.jsonl"
SUMMARY="${REPO}/cache/wsh/${DATE}.summary.json"

cd "${REPO}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"

mkdir -p "${REPO}/cache/wsh"

python -m scripts.wsh_earnings_calendar \
    --watchlist "${WATCHLIST}" \
    --window-days "${WINDOW_DAYS}" \
    --output    "${OUTPUT}" \
    --summary-output "${SUMMARY}"

git add "cache/wsh/${DATE}.jsonl" "cache/wsh/${DATE}.summary.json" || true
if ! git diff --staged --quiet; then
    git commit -m "chore(c13): WSH earnings snapshot ${DATE}" -m "Generated by com.skippalgo.c13.wsh-earnings launchd agent."
    git push origin HEAD || echo "git push failed (non-fatal); will retry tomorrow"
fi
