#!/usr/bin/env bash
# C13 Phase-A — daily local cron driver to push audit artefacts to the
# dedicated `data/phase-a-audit` branch (keeps cron-bot churn off main).
#
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.audit-push.plist
# on Mon-Fri @ 17:30 local time (one hour after US-equity close).
#
# Repo policy: never --force, never --no-verify. Branch is protected on
# the remote; pushes use the same PAT-authenticated origin as the local
# `git push` (gh CLI keyring credentials are reused by git).

set -euo pipefail

REPO="$(cd "$(dirname "$0")/../.." && pwd)"
DATE="$(date -u +%Y-%m-%d)"

cd "${REPO}"

AUDIT="cache/live/incubation_${DATE}.jsonl"
SETUPS="cache/live/setups_${DATE}.jsonl"
GATES="cache/live/gate_status.json"

# Status marker so a degraded run is DETECTABLE rather than silently green.
# Written on every exit path (degraded:* or ok:*). cache/live is gitignored
# on main, so the marker never enters a commit.
STATUS_MARKER="cache/live/.audit_push_status_${DATE}"
mkdir -p cache/live 2>/dev/null || true

if [[ ! -f "${AUDIT}" ]]; then
    echo "audit-push: DEGRADED — no audit artefact at ${AUDIT}. Phase-A produced no" \
         "incubation file today; check com.skippalgo.c13.phase-a (Full-Disk-Access/TCC," \
         "venv path, or upstream trade-cards). Nothing pushed." >&2
    echo "degraded:no-audit-file:$(date -u +%FT%TZ)" > "${STATUS_MARKER}" 2>/dev/null || true
    exit 0
fi

# Commit the audit artefacts onto data/phase-a-audit via a DETACHED git
# worktree. This never switches the branch of the primary working tree, so
# the freshly generated (untracked, gitignored-on-main) cache/live files
# can never collide with the branch's tracked copies — notably the UNDATED
# gate_status.json, which lives on the branch and would otherwise abort a
# plain `git checkout data/phase-a-audit` with "untracked working tree
# files would be overwritten" on every single run.
WORKTREE="$(mktemp -d)/phase-a-audit"
cleanup() {
    git worktree remove --force "${WORKTREE}" 2>/dev/null || true
    rm -rf "$(dirname "${WORKTREE}")" 2>/dev/null || true
}
trap cleanup EXIT

if ! git fetch origin data/phase-a-audit --quiet; then
    echo "audit-push: DEGRADED — 'git fetch origin data/phase-a-audit' failed (branch missing or" \
         "network/auth down). Bootstrap the branch once if it does not exist. Nothing pushed." >&2
    echo "degraded:fetch-failed:$(date -u +%FT%TZ)" > "${STATUS_MARKER}" 2>/dev/null || true
    exit 1
fi

# Check out the remote tip into an isolated worktree on a local
# data/phase-a-audit branch (-B resets it to origin so a stale local
# branch can never cause a non-fast-forward surprise at push time).
git worktree add --quiet -B data/phase-a-audit "${WORKTREE}" origin/data/phase-a-audit

mkdir -p "${WORKTREE}/cache/live"
cp -f "${AUDIT}" "${SETUPS}" "${GATES}" "${WORKTREE}/cache/live/"

git -C "${WORKTREE}" add -f \
    "cache/live/incubation_${DATE}.jsonl" \
    "cache/live/setups_${DATE}.jsonl" \
    "cache/live/gate_status.json"

if git -C "${WORKTREE}" diff --staged --quiet; then
    echo "no audit changes to commit"
    echo "ok:no-change:$(date -u +%FT%TZ)" > "${STATUS_MARKER}" 2>/dev/null || true
    exit 0
fi

git -C "${WORKTREE}" \
    -c user.name="skippalgo-c13-cron" \
    -c user.email="c13-cron@skippalgo.io" \
    commit -m "chore(c13): phase-a audit ${DATE}" \
           -m "Generated by com.skippalgo.c13.audit-push launchd agent."

if git -C "${WORKTREE}" push origin data/phase-a-audit; then
    echo "ok:pushed:$(date -u +%FT%TZ):${AUDIT}" > "${STATUS_MARKER}" 2>/dev/null || true
else
    echo "audit-push: push to data/phase-a-audit failed (non-fatal); will retry tomorrow" >&2
    echo "degraded:push-failed:$(date -u +%FT%TZ)" > "${STATUS_MARKER}" 2>/dev/null || true
fi
