#!/usr/bin/env bash
# C13 / T7.1 — daily local cron driver for WSH earnings calendar pull.
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.wsh-earnings.plist
# on Mon-Fri @ 16:30 local time. Idempotent on the artefact path.

set -euo pipefail

REPO="/Users/steffenpreuss/Downloads/skipp-algo"
VENV="/Users/steffenpreuss/.venv"
WATCHLIST="${REPO}/reports/databento_watchlist_top5_pre1530.csv"
WINDOW_DAYS=14

DATE="$(date -u +%Y-%m-%d)"
OUTPUT="${REPO}/cache/wsh/${DATE}.jsonl"
SUMMARY="${REPO}/cache/wsh/${DATE}.summary.json"

cd "${REPO}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"

mkdir -p "${REPO}/cache/wsh"

python -m scripts.wsh_earnings_calendar \
    --watchlist "${WATCHLIST}" \
    --window-days "${WINDOW_DAYS}" \
    --output    "${OUTPUT}" \
    --summary-output "${SUMMARY}"

git add "cache/wsh/${DATE}.jsonl" "cache/wsh/${DATE}.summary.json" || true
if ! git diff --staged --quiet; then
    git commit -m "chore(c13): WSH earnings snapshot ${DATE}" -m "Generated by com.skippalgo.c13.wsh-earnings launchd agent."
    git push origin HEAD || echo "git push failed (non-fatal); will retry tomorrow"
fi
