#!/usr/bin/env bash
# C13 / T8.2 — daily local cron driver for opening-imbalance collection.
# Invoked by ~/Library/LaunchAgents/com.skippalgo.c13.collect-imbalance.plist
# on Mon-Fri @ 09:28 local time. Idempotent on the artefact path.

set -euo pipefail

# Derive REPO from this script's location so the driver is portable across
# workstations without editing the tracked file. VENV / WATCHLIST can be
# overridden via environment variables (set in the LaunchAgent plist's
# ``EnvironmentVariables`` block) for non-default paths.
REPO="$(cd "$(dirname "$0")/../.." && pwd)"
VENV="${C13_VENV:-${HOME}/.venv}"
WATCHLIST="${C13_WATCHLIST:-${REPO}/reports/databento_watchlist_top5_pre1530.csv}"

DATE="$(date -u +%Y-%m-%d)"
OUTPUT="${REPO}/cache/imbalance/${DATE}.jsonl"
SUMMARY="${REPO}/cache/imbalance/${DATE}.summary.json"

cd "${REPO}"
# shellcheck disable=SC1091
source "${VENV}/bin/activate"

mkdir -p "${REPO}/cache/imbalance"

python -m scripts.collect_opening_imbalances \
    --watchlist "${WATCHLIST}" \
    --output    "${OUTPUT}" \
    --summary-output "${SUMMARY}" \
    --trade-date "${DATE}"

# Best-effort commit + push so the GH-hosted cron sees the artefact.
# Repo policy: never --force, never --no-verify.
git add "cache/imbalance/${DATE}.jsonl" "cache/imbalance/${DATE}.summary.json" || true
if ! git diff --staged --quiet; then
    git commit -m "chore(c13): imbalance snapshot ${DATE}" -m "Generated by com.skippalgo.c13.collect-imbalance launchd agent."
    git push origin HEAD || echo "git push failed (non-fatal); will retry tomorrow"
fi
