"""Generate the design-partner "what you see / what you don't see" page.

Weekly commercial review 2026-08-16 (P2): a design partner faces 1 Lite and
3 Pro surfaces against 17 operator companions and cannot tell what they are
buying. This page answers that on one sheet — and it is GENERATED from the
product cut manifest and the family claim record, so it cannot drift from
the taxonomy or the claim decisions the way hand-written marketing copy
does. ``tests/test_partner_surface_one_pager.py`` regenerates it on every
run and fails on any divergence.

Content boundaries (CLAIMS_REGISTRY.md): no performance claims, no provider
claims, evidence classes stated honestly. Tone and final wording are the
operator's call — the STATUS constant below stays ``draft_pending_operator_review``
until they sign it off in a dated edit.
"""

from __future__ import annotations

import json
from pathlib import Path

from scripts.smc_atomic_write import atomic_write_text

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "artifacts" / "tradingview" / "smc_product_cut_manifest.json"
CLAIM_PATH = ROOT / "docs" / "commercial" / "family_claim_status.json"
OUTPUT_PATH = ROOT / "docs" / "commercial" / "PARTNER_SURFACE_ONE_PAGER.md"

# Flipped by the operator in a dated edit once wording is reviewed;
# the banner below renders as long as it is a draft.
STATUS = "draft_pending_operator_review"


def _script_names(manifest: dict, files: list[str]) -> list[str]:
    by_file = {role["file"]: role["script_name"] for role in manifest["surfaceRoles"]}
    return [by_file[f] for f in files]


def build_one_pager() -> str:
    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    claims = json.loads(CLAIM_PATH.read_text(encoding="utf-8"))

    lite = _script_names(manifest, manifest["litePrimaryFiles"])
    pro = _script_names(manifest, manifest["proPrimaryFiles"])
    n_companions = len(manifest["companionOperatorOnlyFiles"])
    n_internal = len(manifest["internalFiles"])

    families = claims["families"]
    building = sorted(
        name for name, entry in families.items()
        if entry["status"] == "evidence_building"
    )
    incubation = sorted(
        name for name, entry in families.items()
        if entry["status"] == "incubation"
    )

    lines = [
        "<!-- GENERATED by scripts/generate_partner_surface_one_pager.py — do",
        "     not edit by hand; regenerate instead. Inputs: the product cut",
        "     manifest and family_claim_status.json. -->",
        "",
        "# What you see / what you don't see",
        "",
    ]
    if STATUS == "draft_pending_operator_review":
        lines += [
            "> **DRAFT — operator content review pending.** Structure and",
            "> facts are generated from the product taxonomy; tone and final",
            "> wording await the operator's dated sign-off.",
            "",
        ]
    lines += [
        "## What you see",
        "",
        f"- **{lite[0]}** — the chart surface (Lite): structure, context,",
        "  invalidation and explicit uncertainty, decision-first.",
        "- **Pro companions:** " + ", ".join(pro) + ".",
        "",
        "## What you don't see",
        "",
        f"- {n_companions} operator-only companion surfaces and {n_internal}",
        "  internal surfaces: diagnostics, calibration and governance",
        "  tooling. They are the operator plane, not the product — nothing",
        "  you rely on lives only there.",
        "",
        "## What the numbers mean",
        "",
        "- Every published number carries an **evidence class**: MODELED OOS",
        "  (modeled, out-of-sample), PAPER (simulated broker execution) or",
        "  LIVE (real execution). They are never mixed.",
        "- There is **no qualifying live track record today**. The public",
        "  calibration report carries the machine-readable gates",
        "  (`phase1_paper_gate`, `track_record_gate.claimable`) that say so.",
        f"- Event families building evidence: {', '.join(building)}.",
        f"- In incubation (measured, not claimed): {', '.join(incubation)}.",
        "",
        "## Claims boundary",
        "",
        "- What may and may not be claimed is recorded in",
        "  `docs/commercial/CLAIMS_REGISTRY.md`; anything not explicitly",
        "  allowed there is not a claim of this product.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    atomic_write_text(build_one_pager(), OUTPUT_PATH)
    print(f"wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
