#!/usr/bin/env python3
"""Freshness guard + stamper for the hand-authored Pine libraries.

The five shared libraries under ``pine/skipp_*.pine`` ship to TradingView and
are imported by the active suite via ``import preuss_steffen/<lib>/1``. Unlike
the code-generated libraries under ``pine/generated/`` (regenerated by
``smc-library-refresh.yml``), the shared libraries had no scheduled freshness
mechanism and could silently rot.

This module maintains a machine-readable ``// Last refreshed: YYYY-MM-DD``
marker on each shared library:

* ``--check`` exits non-zero when any library is missing a marker or exceeds
  ``--max-age-days`` (used by the scheduled ``pine-library-freshness``
  workflow to turn the build red so a refresh PR is opened).
* ``--update`` stamps today's date into every shared library (the actual
  refresh), writing atomically via ``mkstemp + fdopen + os.replace``.

Pure stdlib. Non-destructive: ``--update`` only rewrites a file when the
marker date actually changes.
"""

from __future__ import annotations

import argparse
import contextlib
import datetime as _dt
import json
import os
import re
import sys
import tempfile
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]

# Active hand-authored shared libraries (mirrors the scope guard in
# tests/test_pine_version_directive.py). Code-generated libraries under
# pine/generated/ and legacy scripts under pine/legacy/ are intentionally
# excluded — they have their own refresh/isolation policies.
SHARED_LIBRARIES: tuple[str, ...] = (
    "pine/skipp_calibration.pine",
    "pine/skipp_indicators.pine",
    "pine/skipp_labels.pine",
    "pine/skipp_math.pine",
    "pine/skipp_scoring.pine",
)

MARKER_PREFIX = "// Last refreshed:"

# Anchored marker: exact ISO date (zero-padded), nothing but trailing space
# allowed after it. A loose ``\d+-\d+-\d+`` would accept malformed dates.
_MARKER_RE = re.compile(
    r"^// Last refreshed:\s*(\d{4}-\d{2}-\d{2})\s*$",
    re.MULTILINE,
)

# The library declaration line the marker is anchored beneath.
_LIBRARY_DECL_RE = re.compile(r"^\s*library\s*\(", re.MULTILINE)

DEFAULT_MAX_AGE_DAYS = 120


def find_marker_date(text: str) -> _dt.date | None:
    """Return the freshness-marker date, or ``None`` if absent/malformed."""
    match = _MARKER_RE.search(text)
    if match is None:
        return None
    try:
        return _dt.date.fromisoformat(match.group(1))
    except ValueError:
        return None


def stamp_marker(text: str, today: _dt.date) -> str:
    """Return ``text`` with a ``// Last refreshed: <today>`` marker.

    Idempotent: replaces an existing marker in place, otherwise inserts a new
    marker line immediately after the ``library(...)`` declaration. Preserves
    the trailing newline convention of the input.
    """
    marker_line = f"{MARKER_PREFIX} {today.isoformat()}"

    if _MARKER_RE.search(text):
        return _MARKER_RE.sub(marker_line, text, count=1)

    lines = text.split("\n")
    for idx, line in enumerate(lines):
        if _LIBRARY_DECL_RE.match(line):
            lines.insert(idx + 1, marker_line)
            return "\n".join(lines)

    # No library() declaration (unexpected for a library file) — prepend.
    return marker_line + "\n" + text


def marker_is_stale(
    marker_date: _dt.date | None,
    today: _dt.date,
    *,
    max_age_days: int,
) -> bool:
    """A missing marker, or one older than ``max_age_days``, is stale."""
    if marker_date is None:
        return True
    return (today - marker_date).days > max_age_days


def _atomic_write_text(path: Path, text: str) -> None:
    """Write ``text`` to ``path`` via mkstemp + fdopen + os.replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except Exception:
        with contextlib.suppress(OSError):
            os.unlink(tmp)
        raise


def update_file(path: Path, today: _dt.date) -> bool:
    """Stamp ``path`` with today's marker. Returns True if the file changed."""
    original = path.read_text(encoding="utf-8")
    stamped = stamp_marker(original, today)
    if stamped == original:
        return False
    _atomic_write_text(path, stamped)
    return True


def check(
    paths: list[Path],
    *,
    today: _dt.date,
    max_age_days: int,
) -> list[str]:
    """Return a list of human-readable staleness problems (empty = all fresh)."""
    problems: list[str] = []
    for path in paths:
        text = path.read_text(encoding="utf-8")
        marker = find_marker_date(text)
        if marker is None:
            problems.append(f"{path.name}: missing '// Last refreshed:' marker")
        elif marker_is_stale(marker, today, max_age_days=max_age_days):
            age = (today - marker).days
            problems.append(
                f"{path.name}: last refreshed {marker.isoformat()} "
                f"({age}d ago, max {max_age_days}d)"
            )
    return problems


def _resolve_paths() -> list[Path]:
    return [_REPO_ROOT / rel for rel in SHARED_LIBRARIES]


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if any library is missing/stale",
    )
    mode.add_argument(
        "--update",
        action="store_true",
        help="stamp today's freshness marker into every shared library",
    )
    parser.add_argument(
        "--max-age-days",
        type=int,
        default=DEFAULT_MAX_AGE_DAYS,
        help=f"staleness threshold in days (default: {DEFAULT_MAX_AGE_DAYS})",
    )
    parser.add_argument(
        "--today",
        default=None,
        help="override today's date (ISO) for deterministic runs/tests",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="emit machine-readable JSON status",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    today = _dt.date.fromisoformat(args.today) if args.today else _dt.date.today()
    paths = _resolve_paths()

    if args.update:
        changed = [p.name for p in paths if update_file(p, today)]
        if args.json:
            print(json.dumps({"updated": changed, "today": today.isoformat()}))
        elif changed:
            print(f"stamped {len(changed)} librar(y/ies): {', '.join(changed)}")
        else:
            print("all libraries already fresh; nothing stamped")
        return 0

    problems = check(paths, today=today, max_age_days=args.max_age_days)
    if args.json:
        print(json.dumps({"problems": problems, "today": today.isoformat()}))
    elif problems:
        print("Stale Pine libraries detected:", file=sys.stderr)
        for problem in problems:
            print(f"  - {problem}", file=sys.stderr)
        print(
            "\nFix: python scripts/pine_library_freshness.py --update",
            file=sys.stderr,
        )
    else:
        print(f"all {len(paths)} shared Pine libraries are fresh")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
