"""Quick-status helper for the Plan 2.8 rollout.

Walks the repo for the artifacts each Plan-2.8 phase is supposed to
produce and prints a compact phase-by-phase report. Read-only.

Each phase has a list of *expected anchors* — file paths or workflow
files. The script reports each anchor as ``ok``, ``missing``, or (for
optional anchors) ``optional-missing``. Operators run this before a
W13 review to confirm everything is in place; CI runs it as a daily
sanity ping.

Exit codes
----------
  0 = all required anchors present (some optional may be missing)
  1 = at least one required anchor missing or unreadable
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from scripts.smc_atomic_write import atomic_write_text

REPO_ROOT = Path(__file__).resolve().parents[1]


PHASES: list[dict[str, Any]] = [
    {
        "name": "Phase 0 - tooltips + grounding",
        "anchors": [
            ("required", "docs/smc_improvement_plan_addendum_2_8_mtf_scope_2026-04-21.md"),
            ("required", "tests/test_plan_2_8_s0_pine_trend_tf_tooltips.py"),
            ("required", "SMC_Core_Engine.pine"),
        ],
    },
    {
        "name": "Phase 1 - 4-TF benchmark + per-TF rollup",
        "anchors": [
            ("required", "scripts/plan_2_8_tf_family_rollup.py"),
            ("required", "tests/test_plan_2_8_tf_family_rollup.py"),
            ("required", "tests/test_plan_2_8_s3_1_chart_tf_expansion.py"),
            ("required", "tests/test_plan_2_8_s3_1_per_tf_partitioning.py"),
            ("required", "tests/test_plan_2_8_rolling_workflow_rollup_wiring.py"),
            ("required", "tests/test_plan_2_8_rolling_workflow_history_wiring.py"),
            ("required", "scripts/plan_2_8_history_archive.py"),
            ("required", "scripts/plan_2_8_history_rotate.py"),
            ("required", "scripts/plan_2_8_history_validate.py"),
            ("required", "tests/test_plan_2_8_history_validate.py"),
            ("required", "scripts/plan_2_8_history_diff.py"),
            ("required", "tests/test_plan_2_8_history_diff.py"),
            ("required", "scripts/plan_2_8_top_movers.py"),
            ("required", "tests/test_plan_2_8_top_movers.py"),
            ("required", "scripts/plan_2_8_alert_snooze.py"),
            ("required", "tests/test_plan_2_8_alert_snooze.py"),
            ("required", "configs/plan_2_8_snoozes.json"),
            ("required", "scripts/plan_2_8_coverage.py"),
            ("required", "tests/test_plan_2_8_coverage.py"),
            ("required", "scripts/plan_2_8_history_stability.py"),
            ("required", "tests/test_plan_2_8_history_stability.py"),
            ("required", "scripts/plan_2_8_snooze_admin.py"),
            ("required", "tests/test_plan_2_8_snooze_admin.py"),
            ("required", "scripts/plan_2_8_snooze_lint.py"),
            ("required", "tests/test_plan_2_8_snooze_lint.py"),
            ("required", "scripts/plan_2_8_history_backfill.py"),
            ("required", "tests/test_plan_2_8_history_backfill.py"),
            ("required", "scripts/plan_2_8_adr_queue.py"),
            ("required", "tests/test_plan_2_8_adr_queue.py"),
            ("required", "scripts/plan_2_8_weekly_runcard.py"),
            ("required", "tests/test_plan_2_8_weekly_runcard.py"),
            ("required", "scripts/plan_2_8_health.py"),
            ("required", "tests/test_plan_2_8_health.py"),
            ("required", "scripts/plan_2_8_changelog_digest.py"),
            ("required", "tests/test_plan_2_8_changelog_digest.py"),
            ("required", "scripts/plan_2_8_runcard_index.py"),
            ("required", "tests/test_plan_2_8_runcard_index.py"),
            ("required", "scripts/plan_2_8_digest_compare.py"),
            ("required", "tests/test_plan_2_8_digest_compare.py"),
            ("required", "scripts/plan_2_8_alert_history_heatmap.py"),
            ("required", "tests/test_plan_2_8_alert_history_heatmap.py"),
            ("required", "scripts/plan_2_8_runbook_toc.py"),
            ("required", "tests/test_plan_2_8_runbook_toc.py"),
            ("required", "scripts/plan_2_8_status_snapshot.py"),
            ("required", "tests/test_plan_2_8_status_snapshot.py"),
            ("required", "scripts/plan_2_8_digest_archive.py"),
            ("required", "tests/test_plan_2_8_digest_archive.py"),
            ("required", "scripts/plan_2_8_runcard_from_status.py"),
            ("required", "tests/test_plan_2_8_runcard_from_status.py"),
            ("required", "scripts/plan_2_8_history_prune.py"),
            ("required", "tests/test_plan_2_8_history_prune.py"),
            ("required", "scripts/plan_2_8_history_export.py"),
            ("required", "tests/test_plan_2_8_history_export.py"),
            ("required", "scripts/plan_2_8_runbook_link_check.py"),
            ("required", "tests/test_plan_2_8_runbook_link_check.py"),
            ("required", "scripts/plan_2_8_snooze_expiry_report.py"),
            ("required", "tests/test_plan_2_8_snooze_expiry_report.py"),
            ("required", "scripts/plan_2_8_manifest.py"),
            ("required", "tests/test_plan_2_8_manifest.py"),
            ("required", "scripts/plan_2_8_manifest_diff.py"),
            ("required", "tests/test_plan_2_8_manifest_diff.py"),
            ("required", "scripts/plan_2_8_digest_schema.py"),
            ("required", "tests/test_plan_2_8_digest_schema.py"),
            ("required", "scripts/plan_2_8_runcard_badge.py"),
            ("required", "tests/test_plan_2_8_runcard_badge.py"),
            ("required", "scripts/plan_2_8_badge_markdown.py"),
            ("required", "tests/test_plan_2_8_badge_markdown.py"),
            ("required", "scripts/plan_2_8_alert_trend.py"),
            ("required", "tests/test_plan_2_8_alert_trend.py"),
            ("required", "scripts/plan_2_8_alert_trend_gate.py"),
            ("required", "tests/test_plan_2_8_alert_trend_gate.py"),
            ("required", "scripts/plan_2_8_digest_to_coverage.py"),
            ("required", "tests/test_plan_2_8_digest_to_coverage.py"),
            ("required", "scripts/plan_2_8_runbook_sections.py"),
            ("required", "tests/test_plan_2_8_runbook_sections.py"),
            ("required", "scripts/plan_2_8_status_ledger.py"),
            ("required", "tests/test_plan_2_8_status_ledger.py"),
            ("required", "scripts/plan_2_8_status_ledger_summarize.py"),
            ("required", "tests/test_plan_2_8_status_ledger_summarize.py"),
            ("required", "scripts/plan_2_8_status_ledger_prune.py"),
            ("required", "tests/test_plan_2_8_status_ledger_prune.py"),
            ("required", "scripts/plan_2_8_weekly_index.py"),
            ("required", "tests/test_plan_2_8_weekly_index.py"),
            ("required", "scripts/plan_2_8_run_stamp.py"),
            ("required", "tests/test_plan_2_8_run_stamp.py"),
            ("required", "scripts/plan_2_8_status_flip_alert.py"),
            ("required", "tests/test_plan_2_8_status_flip_alert.py"),
            ("required", "scripts/plan_2_8_ledger_csv_export.py"),
            ("required", "tests/test_plan_2_8_ledger_csv_export.py"),
            ("required", "scripts/plan_2_8_ledger_validate.py"),
            ("required", "tests/test_plan_2_8_ledger_validate.py"),
            ("required", "scripts/plan_2_8_ledger_stats_json.py"),
            ("required", "tests/test_plan_2_8_ledger_stats_json.py"),
            ("required", "scripts/plan_2_8_artifact_checksum.py"),
            ("required", "tests/test_plan_2_8_artifact_checksum.py"),
            ("required", "scripts/plan_2_8_digest_archive_index.py"),
            ("required", "tests/test_plan_2_8_digest_archive_index.py"),
            ("required", "scripts/plan_2_8_checksum_verify.py"),
            ("required", "tests/test_plan_2_8_checksum_verify.py"),
            ("required", "scripts/plan_2_8_ledger_status_matrix.py"),
            ("required", "tests/test_plan_2_8_ledger_status_matrix.py"),
            ("required", "scripts/plan_2_8_digest_size_budget.py"),
            ("required", "tests/test_plan_2_8_digest_size_budget.py"),
            ("required", "scripts/plan_2_8_ledger_downtime.py"),
            ("required", "tests/test_plan_2_8_ledger_downtime.py"),
            ("required", "scripts/plan_2_8_ledger_weekly_rollup.py"),
            ("required", "tests/test_plan_2_8_ledger_weekly_rollup.py"),
            ("required", "scripts/plan_2_8_digest_index_compare.py"),
            ("required", "tests/test_plan_2_8_digest_index_compare.py"),
            ("required", "scripts/plan_2_8_ledger_uptime_pct.py"),
            ("required", "tests/test_plan_2_8_ledger_uptime_pct.py"),
            ("required", "scripts/plan_2_8_digest_file_manifest.py"),
            ("required", "tests/test_plan_2_8_digest_file_manifest.py"),
            ("required", "scripts/plan_2_8_weekly_summary_index.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_index.py"),
            ("required", "scripts/plan_2_8_ledger_latest_status.py"),
            ("required", "tests/test_plan_2_8_ledger_latest_status.py"),
            ("required", "scripts/plan_2_8_ledger_longest_streak.py"),
            ("required", "tests/test_plan_2_8_ledger_longest_streak.py"),
            ("required", "scripts/plan_2_8_digest_metadata.py"),
            ("required", "tests/test_plan_2_8_digest_metadata.py"),
            ("required", "scripts/plan_2_8_metadata_diff.py"),
            ("required", "tests/test_plan_2_8_metadata_diff.py"),
            ("required", "scripts/plan_2_8_ledger_trend.py"),
            ("required", "tests/test_plan_2_8_ledger_trend.py"),
            ("required", "scripts/plan_2_8_weekly_summary_linkcheck.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_linkcheck.py"),
            ("required", "scripts/plan_2_8_ledger_flap_rate.py"),
            ("required", "tests/test_plan_2_8_ledger_flap_rate.py"),
            ("required", "scripts/plan_2_8_trend_threshold_alert.py"),
            ("required", "tests/test_plan_2_8_trend_threshold_alert.py"),
            ("required", "scripts/plan_2_8_digest_artifact_catalog.py"),
            ("required", "tests/test_plan_2_8_digest_artifact_catalog.py"),
            ("required", "scripts/plan_2_8_ledger_status_today.py"),
            ("required", "tests/test_plan_2_8_ledger_status_today.py"),
            ("required", "scripts/plan_2_8_digest_recent_changes.py"),
            ("required", "tests/test_plan_2_8_digest_recent_changes.py"),
            ("required", "scripts/plan_2_8_weekly_summary_toc_only.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_toc_only.py"),
            ("required", "scripts/plan_2_8_ledger_streak_now.py"),
            ("required", "tests/test_plan_2_8_ledger_streak_now.py"),
            ("required", "scripts/plan_2_8_digest_artifact_age.py"),
            ("required", "tests/test_plan_2_8_digest_artifact_age.py"),
            ("required", "scripts/plan_2_8_ledger_month_summary.py"),
            ("required", "tests/test_plan_2_8_ledger_month_summary.py"),
            ("required", "scripts/plan_2_8_ledger_worst_day.py"),
            ("required", "tests/test_plan_2_8_ledger_worst_day.py"),
            ("required", "scripts/plan_2_8_digest_catalog_diff.py"),
            ("required", "tests/test_plan_2_8_digest_catalog_diff.py"),
            ("required", "scripts/plan_2_8_weekly_summary_section_stats.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_section_stats.py"),
            ("required", "scripts/plan_2_8_ledger_best_day.py"),
            ("required", "tests/test_plan_2_8_ledger_best_day.py"),
            ("required", "scripts/plan_2_8_digest_size_trend.py"),
            ("required", "tests/test_plan_2_8_digest_size_trend.py"),
            ("required", "scripts/plan_2_8_weekly_summary_heading_order.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_heading_order.py"),
            ("required", "scripts/plan_2_8_ledger_status_share.py"),
            ("required", "tests/test_plan_2_8_ledger_status_share.py"),
            ("required", "scripts/plan_2_8_digest_missing_artifacts.py"),
            ("required", "tests/test_plan_2_8_digest_missing_artifacts.py"),
            ("required", "scripts/plan_2_8_weekly_summary_toc_checksum.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_toc_checksum.py"),
            ("required", "scripts/plan_2_8_ledger_hour_histogram.py"),
            ("required", "tests/test_plan_2_8_ledger_hour_histogram.py"),
            ("required", "scripts/plan_2_8_digest_stale_report.py"),
            ("required", "tests/test_plan_2_8_digest_stale_report.py"),
            ("required", "scripts/plan_2_8_weekly_summary_required_sections.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_required_sections.py"),
            ("required", "scripts/plan_2_8_ledger_weekday_histogram.py"),
            ("required", "tests/test_plan_2_8_ledger_weekday_histogram.py"),
            ("required", "scripts/plan_2_8_digest_summary_index.py"),
            ("required", "tests/test_plan_2_8_digest_summary_index.py"),
            ("required", "scripts/plan_2_8_ledger_gap_detector.py"),
            ("required", "tests/test_plan_2_8_ledger_gap_detector.py"),
            ("required", "scripts/plan_2_8_ledger_transition_matrix.py"),
            ("required", "tests/test_plan_2_8_ledger_transition_matrix.py"),
            ("required", "scripts/plan_2_8_digest_hash_inventory.py"),
            ("required", "tests/test_plan_2_8_digest_hash_inventory.py"),
            ("required", "scripts/plan_2_8_weekly_summary_preview.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_preview.py"),
            ("required", "scripts/plan_2_8_ledger_latest_flip.py"),
            ("required", "tests/test_plan_2_8_ledger_latest_flip.py"),
            ("required", "scripts/plan_2_8_digest_filetype_breakdown.py"),
            ("required", "tests/test_plan_2_8_digest_filetype_breakdown.py"),
            ("required", "scripts/plan_2_8_weekly_summary_word_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_word_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_flip.py"),
            ("required", "tests/test_plan_2_8_ledger_first_flip.py"),
            ("required", "scripts/plan_2_8_digest_largest_files.py"),
            ("required", "tests/test_plan_2_8_digest_largest_files.py"),
            ("required", "scripts/plan_2_8_weekly_summary_code_blocks.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_code_blocks.py"),
            ("required", "scripts/plan_2_8_ledger_status_run_length.py"),
            ("required", "tests/test_plan_2_8_ledger_status_run_length.py"),
            ("required", "scripts/plan_2_8_digest_smallest_files.py"),
            ("required", "tests/test_plan_2_8_digest_smallest_files.py"),
            ("required", "scripts/plan_2_8_weekly_summary_link_check.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_link_check.py"),
            ("required", "scripts/plan_2_8_ledger_longest_run.py"),
            ("required", "tests/test_plan_2_8_ledger_longest_run.py"),
            ("required", "scripts/plan_2_8_digest_size_histogram.py"),
            ("required", "tests/test_plan_2_8_digest_size_histogram.py"),
            ("required", "scripts/plan_2_8_weekly_summary_list_stats.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_list_stats.py"),
            ("required", "scripts/plan_2_8_ledger_last_n_summary.py"),
            ("required", "tests/test_plan_2_8_ledger_last_n_summary.py"),
            ("required", "scripts/plan_2_8_digest_mean_size.py"),
            ("required", "tests/test_plan_2_8_digest_mean_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_tables_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_tables_count.py"),
            ("required", "scripts/plan_2_8_ledger_recent_green_ratio.py"),
            ("required", "tests/test_plan_2_8_ledger_recent_green_ratio.py"),
            ("required", "scripts/plan_2_8_digest_median_size.py"),
            ("required", "tests/test_plan_2_8_digest_median_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_emphasis_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_emphasis_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_streaks.py"),
            ("required", "tests/test_plan_2_8_ledger_status_streaks.py"),
            ("required", "scripts/plan_2_8_digest_oldest_newest.py"),
            ("required", "tests/test_plan_2_8_digest_oldest_newest.py"),
            ("required", "scripts/plan_2_8_weekly_summary_image_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_image_count.py"),
            ("required", "scripts/plan_2_8_ledger_distinct_days.py"),
            ("required", "tests/test_plan_2_8_ledger_distinct_days.py"),
            ("required", "scripts/plan_2_8_digest_extension_coverage.py"),
            ("required", "tests/test_plan_2_8_digest_extension_coverage.py"),
            ("required", "scripts/plan_2_8_weekly_summary_paragraph_stats.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_paragraph_stats.py"),
            ("required", "scripts/plan_2_8_ledger_amber_ratio.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_ratio.py"),
            ("required", "scripts/plan_2_8_digest_name_length_stats.py"),
            ("required", "tests/test_plan_2_8_digest_name_length_stats.py"),
            ("required", "scripts/plan_2_8_weekly_summary_heading_hierarchy.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_heading_hierarchy.py"),
            ("required", "scripts/plan_2_8_ledger_red_ratio.py"),
            ("required", "tests/test_plan_2_8_ledger_red_ratio.py"),
            ("required", "scripts/plan_2_8_digest_file_age_stats.py"),
            ("required", "tests/test_plan_2_8_digest_file_age_stats.py"),
            ("required", "scripts/plan_2_8_weekly_summary_blockquote_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_blockquote_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_ratio.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_ratio.py"),
            ("required", "scripts/plan_2_8_digest_empty_files.py"),
            ("required", "tests/test_plan_2_8_digest_empty_files.py"),
            ("required", "scripts/plan_2_8_weekly_summary_hr_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_hr_count.py"),
            ("required", "scripts/plan_2_8_ledger_median_gap.py"),
            ("required", "tests/test_plan_2_8_ledger_median_gap.py"),
            ("required", "scripts/plan_2_8_digest_empty_ratio.py"),
            ("required", "tests/test_plan_2_8_digest_empty_ratio.py"),
            ("required", "scripts/plan_2_8_weekly_summary_inline_code_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_inline_code_count.py"),
            ("required", "scripts/plan_2_8_ledger_unique_statuses.py"),
            ("required", "tests/test_plan_2_8_ledger_unique_statuses.py"),
            ("required", "scripts/plan_2_8_digest_size_sum.py"),
            ("required", "tests/test_plan_2_8_digest_size_sum.py"),
            ("required", "scripts/plan_2_8_weekly_summary_table_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_table_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_green_age.py"),
            ("required", "tests/test_plan_2_8_ledger_first_green_age.py"),
            ("required", "scripts/plan_2_8_digest_largest_file.py"),
            ("required", "tests/test_plan_2_8_digest_largest_file.py"),
            ("required", "scripts/plan_2_8_weekly_summary_link_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_link_count.py"),
            ("required", "scripts/plan_2_8_ledger_latest_captured_at.py"),
            ("required", "tests/test_plan_2_8_ledger_latest_captured_at.py"),
            ("required", "scripts/plan_2_8_digest_smallest_file.py"),
            ("required", "tests/test_plan_2_8_digest_smallest_file.py"),
            ("required", "scripts/plan_2_8_weekly_summary_list_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_list_count.py"),
            ("required", "scripts/plan_2_8_ledger_oldest_captured_at.py"),
            ("required", "tests/test_plan_2_8_ledger_oldest_captured_at.py"),
            ("required", "scripts/plan_2_8_digest_ext_top.py"),
            ("required", "tests/test_plan_2_8_digest_ext_top.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ordered_list_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ordered_list_count.py"),
            ("required", "scripts/plan_2_8_ledger_captures_per_day.py"),
            ("required", "tests/test_plan_2_8_ledger_captures_per_day.py"),
            ("required", "scripts/plan_2_8_digest_tiny_files.py"),
            ("required", "tests/test_plan_2_8_digest_tiny_files.py"),
            ("required", "scripts/plan_2_8_weekly_summary_sha256.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_sha256.py"),
            ("required", "scripts/plan_2_8_ledger_longest_gap.py"),
            ("required", "tests/test_plan_2_8_ledger_longest_gap.py"),
            ("required", "scripts/plan_2_8_digest_duplicate_sizes.py"),
            ("required", "tests/test_plan_2_8_digest_duplicate_sizes.py"),
            ("required", "scripts/plan_2_8_weekly_summary_longest_line.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_longest_line.py"),
            ("required", "scripts/plan_2_8_ledger_green_streak_history.py"),
            ("required", "tests/test_plan_2_8_ledger_green_streak_history.py"),
            ("required", "scripts/plan_2_8_digest_oldest_file.py"),
            ("required", "tests/test_plan_2_8_digest_oldest_file.py"),
            ("required", "scripts/plan_2_8_weekly_summary_footnote_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_footnote_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_red.py"),
            ("required", "tests/test_plan_2_8_ledger_first_red.py"),
            ("required", "scripts/plan_2_8_digest_newest_file.py"),
            ("required", "tests/test_plan_2_8_digest_newest_file.py"),
            ("required", "scripts/plan_2_8_weekly_summary_bold_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_bold_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_amber.py"),
            ("required", "tests/test_plan_2_8_ledger_first_amber.py"),
            ("required", "scripts/plan_2_8_digest_median_mtime.py"),
            ("required", "tests/test_plan_2_8_digest_median_mtime.py"),
            ("required", "scripts/plan_2_8_weekly_summary_strikethrough_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_strikethrough_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_unknown.py"),
            ("required", "tests/test_plan_2_8_ledger_first_unknown.py"),
            ("required", "scripts/plan_2_8_digest_mtime_span.py"),
            ("required", "tests/test_plan_2_8_digest_mtime_span.py"),
            ("required", "scripts/plan_2_8_weekly_summary_reference_defs.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_reference_defs.py"),
            ("required", "scripts/plan_2_8_ledger_last_red.py"),
            ("required", "tests/test_plan_2_8_ledger_last_red.py"),
            ("required", "scripts/plan_2_8_digest_per_ext_bytes.py"),
            ("required", "tests/test_plan_2_8_digest_per_ext_bytes.py"),
            ("required", "scripts/plan_2_8_weekly_summary_html_tag_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_html_tag_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_amber.py"),
            ("required", "tests/test_plan_2_8_ledger_last_amber.py"),
            ("required", "scripts/plan_2_8_digest_word_count.py"),
            ("required", "tests/test_plan_2_8_digest_word_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_autolink_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_autolink_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_unknown.py"),
            ("required", "tests/test_plan_2_8_ledger_last_unknown.py"),
            ("required", "scripts/plan_2_8_digest_line_counts.py"),
            ("required", "tests/test_plan_2_8_digest_line_counts.py"),
            ("required", "scripts/plan_2_8_weekly_summary_emoji_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_emoji_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_first_last.py"),
            ("required", "tests/test_plan_2_8_ledger_status_first_last.py"),
            ("required", "scripts/plan_2_8_digest_basename_length_stats.py"),
            ("required", "tests/test_plan_2_8_digest_basename_length_stats.py"),
            ("required", "scripts/plan_2_8_weekly_summary_shell_fence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_shell_fence_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_run_count.py"),
            ("required", "tests/test_plan_2_8_ledger_status_run_count.py"),
            ("required", "scripts/plan_2_8_digest_longest_filename.py"),
            ("required", "tests/test_plan_2_8_digest_longest_filename.py"),
            ("required", "scripts/plan_2_8_weekly_summary_python_fence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_python_fence_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_run_summary.py"),
            ("required", "tests/test_plan_2_8_ledger_status_run_summary.py"),
            ("required", "scripts/plan_2_8_digest_shortest_filename.py"),
            ("required", "tests/test_plan_2_8_digest_shortest_filename.py"),
            ("required", "scripts/plan_2_8_weekly_summary_yaml_fence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_yaml_fence_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_run_max.py"),
            ("required", "tests/test_plan_2_8_ledger_status_run_max.py"),
            ("required", "scripts/plan_2_8_digest_avg_size.py"),
            ("required", "tests/test_plan_2_8_digest_avg_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_json_fence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_json_fence_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_run_min.py"),
            ("required", "tests/test_plan_2_8_ledger_status_run_min.py"),
            ("required", "scripts/plan_2_8_digest_total_size.py"),
            ("required", "tests/test_plan_2_8_digest_total_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_diff_fence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_diff_fence_count.py"),
            ("required", "scripts/plan_2_8_ledger_avg_run_length.py"),
            ("required", "tests/test_plan_2_8_ledger_avg_run_length.py"),
            ("required", "scripts/plan_2_8_ledger_median_run_length.py"),
            ("required", "tests/test_plan_2_8_ledger_median_run_length.py"),
            ("required", "scripts/plan_2_8_ledger_stddev_run_length.py"),
            ("required", "tests/test_plan_2_8_ledger_stddev_run_length.py"),
            ("required", "scripts/plan_2_8_digest_file_count_by_ext.py"),
            ("required", "tests/test_plan_2_8_digest_file_count_by_ext.py"),
            ("required", "scripts/plan_2_8_weekly_summary_whitespace_ratio.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_whitespace_ratio.py"),
            ("required", "scripts/plan_2_8_ledger_shortest_run.py"),
            ("required", "tests/test_plan_2_8_ledger_shortest_run.py"),
            ("required", "scripts/plan_2_8_digest_uppercase_filename_count.py"),
            ("required", "tests/test_plan_2_8_digest_uppercase_filename_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_digit_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_digit_count.py"),
            ("required", "scripts/plan_2_8_ledger_run_length_range.py"),
            ("required", "tests/test_plan_2_8_ledger_run_length_range.py"),
            ("required", "scripts/plan_2_8_digest_lowercase_filename_count.py"),
            ("required", "tests/test_plan_2_8_digest_lowercase_filename_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_letter_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_letter_count.py"),
            ("required", "scripts/plan_2_8_ledger_mean_run_length_per_status.py"),
            ("required", "tests/test_plan_2_8_ledger_mean_run_length_per_status.py"),
            ("required", "scripts/plan_2_8_weekly_summary_punctuation_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_punctuation_count.py"),
            ("required", "scripts/plan_2_8_ledger_max_run_length_per_status.py"),
            ("required", "tests/test_plan_2_8_ledger_max_run_length_per_status.py"),
            ("required", "scripts/plan_2_8_digest_numeric_basename_count.py"),
            ("required", "tests/test_plan_2_8_digest_numeric_basename_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_space_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_space_count.py"),
            ("required", "scripts/plan_2_8_ledger_min_run_length_per_status.py"),
            ("required", "tests/test_plan_2_8_ledger_min_run_length_per_status.py"),
            ("required", "scripts/plan_2_8_digest_alpha_basename_count.py"),
            ("required", "tests/test_plan_2_8_digest_alpha_basename_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_tab_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_tab_count.py"),
            ("required", "scripts/plan_2_8_ledger_median_run_length_per_status.py"),
            ("required", "tests/test_plan_2_8_ledger_median_run_length_per_status.py"),
            ("required", "scripts/plan_2_8_digest_unique_extension_count.py"),
            ("required", "tests/test_plan_2_8_digest_unique_extension_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_newline_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_newline_count.py"),
            ("required", "scripts/plan_2_8_ledger_total_run_length_per_status.py"),
            ("required", "tests/test_plan_2_8_ledger_total_run_length_per_status.py"),
            ("required", "scripts/plan_2_8_digest_symlink_count.py"),
            ("required", "tests/test_plan_2_8_digest_symlink_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_cr_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_cr_count.py"),
            ("required", "scripts/plan_2_8_ledger_run_length_iqr.py"),
            ("required", "tests/test_plan_2_8_ledger_run_length_iqr.py"),
            ("required", "scripts/plan_2_8_digest_directory_count.py"),
            ("required", "tests/test_plan_2_8_digest_directory_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_crlf_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_crlf_count.py"),
            ("required", "scripts/plan_2_8_ledger_run_length_variance.py"),
            ("required", "tests/test_plan_2_8_ledger_run_length_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_trailing_newline.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_trailing_newline.py"),
            ("required", "scripts/plan_2_8_ledger_observation_count.py"),
            ("required", "tests/test_plan_2_8_ledger_observation_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_starts_with_heading.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_starts_with_heading.py"),
            ("required", "scripts/plan_2_8_ledger_observations_by_status.py"),
            ("required", "tests/test_plan_2_8_ledger_observations_by_status.py"),
            ("required", "scripts/plan_2_8_weekly_summary_last_line_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_last_line_length.py"),
            ("required", "scripts/plan_2_8_ledger_rarest_status.py"),
            ("required", "tests/test_plan_2_8_ledger_rarest_status.py"),
            ("required", "scripts/plan_2_8_weekly_summary_first_line_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_first_line_length.py"),
            ("required", "scripts/plan_2_8_ledger_most_common_status.py"),
            ("required", "tests/test_plan_2_8_ledger_most_common_status.py"),
            ("required", "scripts/plan_2_8_weekly_summary_mean_line_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_mean_line_length.py"),
            ("required", "scripts/plan_2_8_ledger_status_set_size.py"),
            ("required", "tests/test_plan_2_8_ledger_status_set_size.py"),
            ("required", "scripts/plan_2_8_digest_max_file_size.py"),
            ("required", "tests/test_plan_2_8_digest_max_file_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_median_line_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_median_line_length.py"),
            ("required", "scripts/plan_2_8_ledger_status_coverage.py"),
            ("required", "tests/test_plan_2_8_ledger_status_coverage.py"),
            ("required", "scripts/plan_2_8_digest_min_file_size.py"),
            ("required", "tests/test_plan_2_8_digest_min_file_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_max_line_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_max_line_length.py"),
            ("required", "scripts/plan_2_8_ledger_green_ratio.py"),
            ("required", "tests/test_plan_2_8_ledger_green_ratio.py"),
            ("required", "scripts/plan_2_8_digest_file_size_stddev.py"),
            ("required", "tests/test_plan_2_8_digest_file_size_stddev.py"),
            ("required", "scripts/plan_2_8_weekly_summary_line_length_stddev.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_line_length_stddev.py"),
            ("required", "scripts/plan_2_8_ledger_status_entropy.py"),
            ("required", "tests/test_plan_2_8_ledger_status_entropy.py"),
            ("required", "scripts/plan_2_8_digest_file_size_range.py"),
            ("required", "tests/test_plan_2_8_digest_file_size_range.py"),
            ("required", "scripts/plan_2_8_weekly_summary_unique_word_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_unique_word_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_observation.py"),
            ("required", "tests/test_plan_2_8_ledger_first_observation.py"),
            ("required", "scripts/plan_2_8_digest_missing_files.py"),
            ("required", "tests/test_plan_2_8_digest_missing_files.py"),
            ("required", "scripts/plan_2_8_weekly_summary_trailing_whitespace_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_trailing_whitespace_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_observation.py"),
            ("required", "tests/test_plan_2_8_ledger_last_observation.py"),
            ("required", "scripts/plan_2_8_digest_file_size_median.py"),
            ("required", "tests/test_plan_2_8_digest_file_size_median.py"),
            ("required", "scripts/plan_2_8_weekly_summary_longest_word.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_longest_word.py"),
            ("required", "scripts/plan_2_8_ledger_malformed_count.py"),
            ("required", "tests/test_plan_2_8_ledger_malformed_count.py"),
            ("required", "scripts/plan_2_8_digest_readable_fraction.py"),
            ("required", "tests/test_plan_2_8_digest_readable_fraction.py"),
            ("required", "scripts/plan_2_8_weekly_summary_avg_word_length.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_avg_word_length.py"),
            ("required", "scripts/plan_2_8_ledger_blank_line_count.py"),
            ("required", "tests/test_plan_2_8_ledger_blank_line_count.py"),
            ("required", "scripts/plan_2_8_digest_writable_fraction.py"),
            ("required", "tests/test_plan_2_8_digest_writable_fraction.py"),
            ("required", "scripts/plan_2_8_weekly_summary_heading_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_heading_count.py"),
            ("required", "scripts/plan_2_8_ledger_unique_days.py"),
            ("required", "tests/test_plan_2_8_ledger_unique_days.py"),
            ("required", "scripts/plan_2_8_digest_total_line_count.py"),
            ("required", "tests/test_plan_2_8_digest_total_line_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_backtick_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_backtick_count.py"),
            ("required", "scripts/plan_2_8_ledger_observations_per_day_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_observations_per_day_mean.py"),
            ("required", "scripts/plan_2_8_digest_file_size_mean.py"),
            ("required", "tests/test_plan_2_8_digest_file_size_mean.py"),
            ("required", "scripts/plan_2_8_weekly_summary_checkbox_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_checkbox_count.py"),
            ("required", "scripts/plan_2_8_ledger_record_byte_size_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_record_byte_size_mean.py"),
            ("required", "scripts/plan_2_8_digest_total_byte_size.py"),
            ("required", "tests/test_plan_2_8_digest_total_byte_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_vowel_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_vowel_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_streak_max.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_streak_max.py"),
            ("required", "scripts/plan_2_8_digest_file_size_variance.py"),
            ("required", "tests/test_plan_2_8_digest_file_size_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_uppercase_letter_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_uppercase_letter_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_streak_max.py"),
            ("required", "tests/test_plan_2_8_ledger_red_streak_max.py"),
            ("required", "scripts/plan_2_8_digest_largest_file_size.py"),
            ("required", "tests/test_plan_2_8_digest_largest_file_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_lowercase_letter_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_lowercase_letter_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_streak_max.py"),
            ("required", "tests/test_plan_2_8_ledger_green_streak_max.py"),
            ("required", "scripts/plan_2_8_digest_smallest_file_size.py"),
            ("required", "tests/test_plan_2_8_digest_smallest_file_size.py"),
            ("required", "scripts/plan_2_8_weekly_summary_whitespace_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_whitespace_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_streak_max.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_streak_max.py"),
            ("required", "scripts/plan_2_8_weekly_summary_tab_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_tab_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_green_index.py"),
            ("required", "tests/test_plan_2_8_ledger_first_green_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_hash_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_hash_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_amber_index.py"),
            ("required", "tests/test_plan_2_8_ledger_first_amber_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_non_ascii_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_non_ascii_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_red_index.py"),
            ("required", "tests/test_plan_2_8_ledger_first_red_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_sentence_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_sentence_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_unknown_index.py"),
            ("required", "tests/test_plan_2_8_ledger_first_unknown_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_question_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_question_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_green_index.py"),
            ("required", "tests/test_plan_2_8_ledger_last_green_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_exclamation_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_exclamation_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_amber_index.py"),
            ("required", "tests/test_plan_2_8_ledger_last_amber_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_comma_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_comma_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_red_index.py"),
            ("required", "tests/test_plan_2_8_ledger_last_red_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_semicolon_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_semicolon_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_unknown_index.py"),
            ("required", "tests/test_plan_2_8_ledger_last_unknown_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_colon_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_colon_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_mean.py"),
            ("required", "scripts/plan_2_8_weekly_summary_quote_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_quote_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_mean.py"),
            ("required", "scripts/plan_2_8_weekly_summary_apostrophe_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_apostrophe_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_mean.py"),
            ("required", "scripts/plan_2_8_weekly_summary_pipe_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_pipe_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_mean.py"),
            ("required", "scripts/plan_2_8_weekly_summary_underscore_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_underscore_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_transition_count.py"),
            ("required", "tests/test_plan_2_8_ledger_status_transition_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_plus_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_plus_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_transition_index.py"),
            ("required", "tests/test_plan_2_8_ledger_first_transition_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_minus_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_minus_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_last_transition_index.py"),
            ("required", "tests/test_plan_2_8_ledger_last_transition_index.py"),
            ("required", "scripts/plan_2_8_weekly_summary_equal_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_equal_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_transition_rate.py"),
            ("required", "tests/test_plan_2_8_ledger_status_transition_rate.py"),
            ("required", "scripts/plan_2_8_weekly_summary_asterisk_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_asterisk_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_median.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_median.py"),
            ("required", "scripts/plan_2_8_weekly_summary_slash_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_slash_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_median.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_median.py"),
            ("required", "scripts/plan_2_8_weekly_summary_backslash_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_backslash_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_median.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_median.py"),
            ("required", "scripts/plan_2_8_weekly_summary_caret_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_caret_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_median.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_median.py"),
            ("required", "scripts/plan_2_8_weekly_summary_tilde_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_tilde_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_stddev.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_stddev.py"),
            ("required", "scripts/plan_2_8_weekly_summary_grave_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_grave_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_stddev.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_stddev.py"),
            ("required", "scripts/plan_2_8_weekly_summary_dollar_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_dollar_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_stddev.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_stddev.py"),
            ("required", "scripts/plan_2_8_weekly_summary_at_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_at_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_stddev.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_stddev.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ampersand_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ampersand_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_variance.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_percent_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_percent_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_variance.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_lt_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_lt_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_variance.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_gt_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_gt_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_variance.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_variance.py"),
            ("required", "scripts/plan_2_8_weekly_summary_paren_open_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_paren_open_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_min.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_min.py"),
            ("required", "scripts/plan_2_8_weekly_summary_paren_close_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_paren_close_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_min.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_min.py"),
            ("required", "scripts/plan_2_8_weekly_summary_bracket_open_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_bracket_open_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_min.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_min.py"),
            ("required", "scripts/plan_2_8_weekly_summary_bracket_close_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_bracket_close_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_min.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_min.py"),
            ("required", "scripts/plan_2_8_weekly_summary_brace_open_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_brace_open_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_index_max.py"),
            ("required", "tests/test_plan_2_8_ledger_green_index_max.py"),
            ("required", "scripts/plan_2_8_weekly_summary_brace_close_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_brace_close_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_index_max.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_index_max.py"),
            ("required", "scripts/plan_2_8_weekly_summary_newline_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_newline_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_index_max.py"),
            ("required", "tests/test_plan_2_8_ledger_red_index_max.py"),
            ("required", "scripts/plan_2_8_weekly_summary_carriage_return_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_carriage_return_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_index_max.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_index_max.py"),
            ("required", "scripts/plan_2_8_weekly_summary_form_feed_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_form_feed_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_streak_count.py"),
            ("required", "tests/test_plan_2_8_ledger_green_streak_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_vertical_tab_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_vertical_tab_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_streak_count.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_streak_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_null_byte_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_null_byte_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_streak_count.py"),
            ("required", "tests/test_plan_2_8_ledger_red_streak_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_space_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_space_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_streak_count.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_streak_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ascii_printable_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ascii_printable_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_green_first_last_index_span.py"),
            ("required", "tests/test_plan_2_8_ledger_green_first_last_index_span.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ascii_control_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ascii_control_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_amber_first_last_index_span.py"),
            ("required", "tests/test_plan_2_8_ledger_amber_first_last_index_span.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ascii_letter_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ascii_letter_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_red_first_last_index_span.py"),
            ("required", "tests/test_plan_2_8_ledger_red_first_last_index_span.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ascii_hexdigit_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ascii_hexdigit_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unknown_first_last_index_span.py"),
            ("required", "tests/test_plan_2_8_ledger_unknown_first_last_index_span.py"),
            ("required", "scripts/plan_2_8_weekly_summary_ascii_alnum_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_ascii_alnum_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_unique_status_count.py"),
            ("required", "tests/test_plan_2_8_ledger_unique_status_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_bom_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_bom_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_captured_at_present_count.py"),
            ("required", "tests/test_plan_2_8_ledger_captured_at_present_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_zero_width_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_zero_width_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_captured_at_missing_count.py"),
            ("required", "tests/test_plan_2_8_ledger_captured_at_missing_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_line_separator_char_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_line_separator_char_count.py"),
            ("required", "scripts/plan_2_8_ledger_invalid_status_count.py"),
            ("required", "tests/test_plan_2_8_ledger_invalid_status_count.py"),
            ("required", "scripts/plan_2_8_ledger_status_mode_count.py"),
            ("required", "tests/test_plan_2_8_ledger_status_mode_count.py"),
            ("required", "scripts/plan_2_8_ledger_first_record_status.py"),
            ("required", "tests/test_plan_2_8_ledger_first_record_status.py"),
            ("required", "scripts/plan_2_8_ledger_last_record_status.py"),
            ("required", "tests/test_plan_2_8_ledger_last_record_status.py"),
            ("required", "scripts/plan_2_8_ledger_total_byte_size.py"),
            ("required", "tests/test_plan_2_8_ledger_total_byte_size.py"),
            ("required", "scripts/plan_2_8_ledger_byte_size_per_line_mean.py"),
            ("required", "tests/test_plan_2_8_ledger_byte_size_per_line_mean.py"),
            ("required", "scripts/plan_2_8_ledger_nonblank_line_count.py"),
            ("required", "tests/test_plan_2_8_ledger_nonblank_line_count.py"),
            ("required", "scripts/plan_2_8_ledger_schema_version_count.py"),
            ("required", "tests/test_plan_2_8_ledger_schema_version_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_fenced_code_block_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_fenced_code_block_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_horizontal_rule_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_horizontal_rule_count.py"),
            ("required", "scripts/plan_2_8_ledger_json_valid_count.py"),
            ("required", "tests/test_plan_2_8_ledger_json_valid_count.py"),
            ("required", "scripts/plan_2_8_ledger_json_invalid_count.py"),
            ("required", "tests/test_plan_2_8_ledger_json_invalid_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_table_row_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_table_row_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_table_separator_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_table_separator_count.py"),
            ("required", "scripts/plan_2_8_ledger_field_key_count.py"),
            ("required", "tests/test_plan_2_8_ledger_field_key_count.py"),
            ("required", "scripts/plan_2_8_ledger_null_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_null_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_bool_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_bool_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_number_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_number_value_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_trailing_colon_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_trailing_colon_count.py"),
            ("required", "scripts/plan_2_8_ledger_string_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_string_value_count.py"),
            ("required", "scripts/plan_2_8_weekly_summary_leading_colon_count.py"),
            ("required", "tests/test_plan_2_8_weekly_summary_leading_colon_count.py"),
            ("required", "scripts/plan_2_8_ledger_array_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_array_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_object_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_object_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_int_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_int_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_float_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_float_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_empty_string_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_empty_string_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_zero_number_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_zero_number_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_negative_number_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_negative_number_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_positive_number_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_positive_number_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_empty_array_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_empty_array_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_empty_object_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_empty_object_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_nested_array_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_nested_array_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_nested_object_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_nested_object_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_true_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_true_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_false_value_count.py"),
            ("required", "tests/test_plan_2_8_ledger_false_value_count.py"),
            ("required", "scripts/plan_2_8_ledger_top_key_count_total.py"),
            ("required", "tests/test_plan_2_8_ledger_top_key_count_total.py"),
            ("required", "scripts/plan_2_8_ledger_top_key_count_max.py"),
            ("required", "tests/test_plan_2_8_ledger_top_key_count_max.py"),
            ("required", "scripts/plan_2_8_ledger_top_key_count_min.py"),
            ("required", "tests/test_plan_2_8_ledger_top_key_count_min.py"),
            ("required", "scripts/plan_2_8_ledger_top_key_count_unique.py"),
            ("required", "tests/test_plan_2_8_ledger_top_key_count_unique.py"),
            ("required", "scripts/plan_2_8_alert_history.py"),
            ("required", "tests/test_plan_2_8_alert_history.py"),
            ("required", "scripts/plan_2_8_alert_history_summary.py"),
            ("required", "tests/test_plan_2_8_alert_history_summary.py"),
            ("required", "scripts/plan_2_8_digest_rollup.py"),
            ("required", "tests/test_plan_2_8_digest_rollup.py"),
            ("required", ".github/workflows/plan-2-8-monthly-digest.yml"),
            ("required", "tests/test_plan_2_8_monthly_digest_workflow.py"),
            ("required", "tests/test_plan_2_8_rolling_workflow_rotate_wiring.py"),
            ("required", "tests/test_plan_2_8_rolling_workflow_validate_wiring.py"),
            ("required", "scripts/plan_2_8_trend_digest.py"),
            ("required", "tests/test_plan_2_8_trend_digest_issue_body.py"),
            ("required", "tests/test_plan_2_8_weekly_digest_issue_wiring.py"),
            ("required", ".github/workflows/smc-measurement-benchmark-rolling.yml"),
            ("required", ".github/workflows/plan-2-8-weekly-digest.yml"),
        ],
    },
    {
        "name": "Phase 2 - A/B bundle builder",
        "anchors": [
            ("required", "scripts/plan_2_8_q4_gate_bundle_builder.py"),
            ("required", "tests/test_plan_2_8_q4_gate_bundle_builder.py"),
            ("optional", "artifacts/plan_2_8_q4_gate_bundle.json"),
        ],
    },
    {
        "name": "Phase 3 - Q4 gate evaluator + dryrun + ADR",
        "anchors": [
            ("required", "scripts/plan_2_8_q4_gate_evaluator.py"),
            ("required", "tests/test_plan_2_8_q4_gate_evaluator.py"),
            ("required", ".github/workflows/plan-2-8-q4-gate-dryrun.yml"),
            ("required", "tests/test_plan_2_8_q4_gate_workflow.py"),
            ("required", "scripts/append_adr.py"),
            ("required", "tests/test_append_adr.py"),
            ("required", "docs/DECISIONS.md"),
            ("required", "tests/test_docs_decisions_adr.py"),
            ("required", "docs/plan_2_8_rollout_runbook.md"),
            ("required", "tests/test_plan_2_8_rollout_runbook.py"),
        ],
    },
]


def evaluate_status(repo_root: Path = REPO_ROOT) -> dict[str, Any]:
    """Walk the phase anchor list under ``repo_root`` and return a status dict."""
    phases_out: list[dict[str, Any]] = []
    overall_ok = True
    for phase in PHASES:
        anchors_out: list[dict[str, Any]] = []
        phase_ok = True
        for kind, rel in phase["anchors"]:
            path = repo_root / rel
            present = path.exists()
            if not present and kind == "required":
                status = "missing"
                phase_ok = False
                overall_ok = False
            elif not present:
                status = "optional-missing"
            else:
                status = "ok"
            anchors_out.append({"path": rel, "kind": kind, "status": status})
        phases_out.append({
            "name": phase["name"],
            "ok": phase_ok,
            "anchors": anchors_out,
        })
    return {
        "schema_version": 1,
        "ok": overall_ok,
        "phases": phases_out,
    }


def render_markdown(status: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("# Plan 2.8 phase status")
    lines.append("")
    lines.append(f"overall: **{'ok' if status['ok'] else 'INCOMPLETE'}**")
    lines.append("")
    for phase in status["phases"]:
        marker = "ok" if phase["ok"] else "INCOMPLETE"
        lines.append(f"## {phase['name']}  ({marker})")
        lines.append("")
        lines.append("| anchor | kind | status |")
        lines.append("| --- | --- | :---: |")
        for a in phase["anchors"]:
            lines.append(f"| `{a['path']}` | {a['kind']} | {a['status']} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"

# F-V6-A1.1 (2026-05-02): bootstrap root logging so the logger.info(...)
# progress messages this entry point emits actually surface in CI logs
# (default WARNING-only handler would drop them). Extends F-V5-A1-2 / #2012
# from the priority entry-point set to plan_2_8 aggregators + showcase.
try:
    from scripts._logging_init import init_cli_logging
except ImportError:  # script-style invocation: `python scripts/X.py`
    import sys as _v6a11_sys
    from pathlib import Path as _v6a11_Path

    _v6a11_sys.path.insert(0, str(_v6a11_Path(__file__).resolve().parents[1]))
    from scripts._logging_init import init_cli_logging  # type: ignore[no-redef]




def main(argv: list[str] | None = None) -> int:
    init_cli_logging()  # F-V6-A1.1 (2026-05-02)
    parser = argparse.ArgumentParser(description="Plan 2.8 rollout status report.")
    parser.add_argument("--repo-root", type=Path, default=REPO_ROOT)
    parser.add_argument("--format", choices=("md", "json"), default="md")
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args(argv)

    status = evaluate_status(args.repo_root)
    body = (
        render_markdown(status) if args.format == "md"
        else json.dumps(status, indent=2) + "\n"
    )
    if args.output is not None:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(body, args.output)
    print(body, end="")
    return 0 if status["ok"] else 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
