#!/usr/bin/env python3
"""Machine half of the deliberate R1 re-attestation.

``hold_r1_attested_sources`` keeps the 9x-per-day library refresh away from
the two R1-attested companions and defers their import-pin bump to "a
deliberate re-attestation PR" -- one that moves the source, measures
TradingView, records a new dated artifact and repoints the registered
evidence together. Operator decision 2026-08-04: that PR is automated.

This module generates the dated artifact from measurements that already
exist -- the rollout driver's write report and its independent verify-only
report from the same workflow run -- and appends it to the supersession
chain that ``scripts.smc_r1_rollout_contract`` derives its evidence paths
from. It never talks to TradingView itself.

It is fail-closed on the boundary of what a machine may honestly attest:

* **Pin-only supersession, proven by hash reconstruction.** The current
  Event Overlay text with its import pin swapped back to the prior attested
  version must hash to the prior attested SHA-256. Any other change --
  a comment, whitespace, a reordered input -- misses the reconstruction and
  the generator refuses: that change class needs a human attestation.
* **Exit Signal must be byte-identical** to the prior attested value, or the
  carried-over replay evidence would describe a source nobody replayed.
* **The reports must prove a clean rollout**: every save succeeded, the
  verify pass read back zero source drift and zero binding mismatches,
  out-of-band drift clean, both passes on the same commit.

The four attended-observation gates stay listed as open, exactly as on the
prior artifact: nothing here re-measures them, and the artifact says so.

Where the measurement came from is recorded, never assumed. The automated
path names its GitHub Actions run; an attended session at a workstation --
which has no run id -- names its operator and binds the two report files by
SHA-256 instead. Both are honest; the local one is narrower, and the artifact
carries that difference in its own limitations rather than borrowing the
shape of a CI run it never had.

Run as a module -- ``python -m scripts.smc_r1_generate_attestation`` -- from
the repository root (same import rationale as check_r1_attested_sources).
The rollout contract JSON is regenerated by a SEPARATE
``python -m scripts.smc_r1_rollout_contract`` invocation afterwards: the
contract module resolves the chain head at import time, so a fresh
interpreter is the honest way to read the chain this module just extended.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
from typing import Any, Final

from scripts.smc_atomic_write import atomic_write_text

_PIN_RE: Final = re.compile(
    r"import preuss_steffen/smc_micro_profiles_generated/(\d+) as mp"
)

_EVENT_NAME: Final = "SMC Event Overlay"
_EXIT_NAME: Final = "SMC Exit Signal"


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _pin_version(text: str) -> int:
    match = _PIN_RE.search(text)
    if match is None:
        raise ValueError(
            "Event Overlay carries no micro-profile import pin -- refusing to "
            "classify a source this generator does not understand"
        )
    return int(match.group(1))


def classify_event_overlay_change(
    current_text: str, *, prior_version: int, prior_sha256: str
) -> str:
    """``identical`` | ``pin-only`` | ``other`` -- by reconstruction, not diff.

    ``pin-only`` holds exactly when swapping the current import pin back to
    ``prior_version`` reproduces the prior attested bytes. That is the entire
    change class the automated chain may attest; everything else is ``other``
    and needs a human.
    """
    _pin_version(current_text)  # loud refusal when the pin line is missing
    if _sha256_text(current_text) == prior_sha256:
        return "identical"
    reconstructed = _PIN_RE.sub(
        f"import preuss_steffen/smc_micro_profiles_generated/{prior_version} as mp",
        current_text,
        count=1,
    )
    if _sha256_text(reconstructed) == prior_sha256:
        return "pin-only"
    return "other"


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


SOURCE_CHANGE_GATE: Final = "R1-SOURCE-CHANGE-ATTESTATION"

_ISO_INSTANT_RE: Final = re.compile(
    r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})"
)

# Operators fill this artifact from a template. A field left on its marker is
# the failure mode that costs the most: every other check passes, the run goes
# green, and the placeholder is frozen into the permanent evidence record where
# it reads like a statement. Found by filling the template deliberately badly
# on 2026-08-12 -- an unfilled `behaviourReviewed` sailed through, because a
# non-empty string is exactly what a placeholder is.
_PLACEHOLDER_MARKERS: Final = ("<<", ">>", "TODO", "FIXME")


def _reject_unfilled_placeholders(node: object, path: str = "attestation") -> None:
    if isinstance(node, dict):
        for key, value in node.items():
            _reject_unfilled_placeholders(value, f"{path}.{key}")
    elif isinstance(node, list):
        for index, value in enumerate(node):
            _reject_unfilled_placeholders(value, f"{path}[{index}]")
    elif isinstance(node, str):
        for marker in _PLACEHOLDER_MARKERS:
            _require(
                marker not in node,
                f"{path} still carries the template marker {marker!r}: "
                "an unfilled field would be frozen into the evidence record "
                "as though someone had written it",
            )


def validate_source_change_attestation(
    attestation: dict, *, overlay_sha: str, exit_sha: str
) -> None:
    """Refuse a human attestation that does not describe THIS tree.

    The point of the artifact is to let a change class the machine cannot
    reconstruct through the chain anyway. That only stays honest if the
    attestation is bound to the bytes it attests: an operator may vouch for a
    source they reviewed, never for one they did not see. Every field below is
    checked against what this generator computed from the working tree, so a
    stale or copied attestation fails instead of carrying a claim forward.

    It follows the OPERATOR_OBSERVATION_EVIDENCE precedent in
    scripts/smc_r1_rollout_contract.py -- a dated, checked-in artifact naming
    its observer -- and adds the hash binding that precedent does not need.
    """
    _require(
        attestation.get("gate") == SOURCE_CHANGE_GATE,
        f"attestation gate is {attestation.get('gate')!r}, expected {SOURCE_CHANGE_GATE!r}",
    )
    _reject_unfilled_placeholders(attestation)
    captured = attestation.get("capturedAt")
    _require(
        isinstance(captured, str) and _ISO_INSTANT_RE.fullmatch(captured) is not None,
        f"attestation capturedAt is {captured!r}, expected an ISO-8601 instant "
        "like 2026-08-13T09:15:00Z -- an observation without a time is not dated",
    )
    observer = attestation.get("observer")
    _require(
        isinstance(observer, str) and observer.strip() != "",
        "attestation names no observer -- an unsigned attestation attests nothing",
    )
    _require(
        isinstance(attestation.get("changeCharacter"), str)
        and attestation["changeCharacter"].strip() != "",
        "attestation does not say what changed (changeCharacter)",
    )

    sources = attestation.get("sources")
    _require(isinstance(sources, dict), "attestation carries no sources block")
    for name, expected_sha in ((_EVENT_NAME, overlay_sha), (_EXIT_NAME, exit_sha)):
        _require(name in sources, f"attestation does not cover {name}")
        attested = sources[name].get("attestedSha256")
        _require(
            attested == expected_sha,
            f"attestation for {name} names sha256 {attested} but this tree holds "
            f"{expected_sha} -- it attests a source nobody in this run reviewed",
        )
        reviewed = sources[name].get("behaviourReviewed")
        _require(
            isinstance(reviewed, str) and reviewed.strip() != "",
            f"attestation for {name} does not record what was reviewed",
        )

    replay = attestation.get("replay")
    _require(isinstance(replay, dict), "attestation carries no replay block")
    _require(
        replay.get("status") == "re-run",
        "a non-pin change may not carry replay evidence over: the carried "
        f"replay would describe a source nobody replayed (status is "
        f"{replay.get('status')!r})",
    )
    _require(
        replay.get("attestedExitSha256") == exit_sha,
        "the replay block attests a different SMC Exit Signal than this tree holds",
    )
    _require(
        isinstance(replay.get("evidence"), str) and replay["evidence"].strip() != "",
        "the replay block names no evidence artifact",
    )
    cases = replay.get("passedLogicalCases")
    _require(
        isinstance(cases, int) and cases > 0,
        f"the replay block reports {cases!r} passed logical cases",
    )


GITHUB_RUN_ORIGIN: Final = "github-actions-run"
LOCAL_SESSION_ORIGIN: Final = "local-attended-session"


def _report_provenance(path: Path, repo_root: Path | None) -> dict[str, Any]:
    """Bind a report file to the artifact by SHA-256, and say if it survives.

    A workflow run keeps its reports as run artifacts; a workstation does not.
    Recording the digest costs nothing and turns "these two files were the
    measurement" from a claim into something a reader can re-check for as long
    as the files exist -- which the ``retainedInRepo`` flag states plainly
    rather than leaving to assumption.
    """
    resolved = path.resolve()
    # Both sides must be resolved or the comparison silently loses: on macOS a
    # /var/... root never contains a /private/var/... file, so a report sitting
    # in the repo would be recorded as "not retained" -- a false statement in
    # the conservative direction, which is still a false statement.
    root = repo_root.resolve() if repo_root is not None else None
    inside = root is not None and resolved.is_relative_to(root)
    return {
        "path": resolved.relative_to(root).as_posix() if inside else str(resolved),
        "retainedInRepo": bool(inside),
        "sha256": hashlib.sha256(resolved.read_bytes()).hexdigest(),
    }


def github_run_provenance(run_id: int, *, workflow: str) -> dict[str, Any]:
    """Provenance for the automated path: a GitHub Actions run identifies it."""
    _require(
        isinstance(run_id, int) and run_id > 0,
        f"run id is {run_id!r}, expected a positive GitHub Actions run id",
    )
    return {
        "kind": GITHUB_RUN_ORIGIN,
        "runId": run_id,
        "workflow": workflow,
        "reference": f"GitHub Actions run {run_id}",
        "note": (
            "Dispatched, measured and recorded inside one workflow run; the "
            "run's own logs and artifacts are the second copy of this evidence."
        ),
    }


def local_session_provenance(
    *,
    operator: str,
    workflow: str,
    write_report_path: Path,
    verify_report_path: Path,
    repo_root: Path | None = None,
) -> dict[str, Any]:
    """Provenance for a measurement taken at a workstation, said out loud.

    The automated chain identifies its measurement by a GitHub run id. An
    attended local session has none, and inventing one would put a false
    statement about where the measurement came from into a permanent evidence
    record -- the exact failure this generator exists to prevent. So the local
    session is recorded as what it is: a named operator, at a workstation, with
    the two report files bound by SHA-256 in place of a run to look up.

    This is strictly narrower than the CI path, and the artifact says so: no
    workflow log holds a second copy, and the reports may not outlive the
    session. It is offered because the alternative in practice is a fabricated
    run id, not a better measurement.
    """
    _require(
        isinstance(operator, str) and operator.strip() != "",
        "a local attended session must name the operator who ran it -- an "
        "unattributed local measurement attests nothing",
    )
    return {
        "kind": LOCAL_SESSION_ORIGIN,
        "runId": None,
        "workflow": workflow,
        "operator": operator,
        "reference": f"the local attended session run by {operator}",
        "reports": {
            "write": _report_provenance(write_report_path, repo_root),
            "verify": _report_provenance(verify_report_path, repo_root),
        },
        "note": (
            "Run from a workstation, not from CI. There is no GitHub run id "
            "and no workflow log holding a second copy of these reports; the "
            "two report files are bound here by SHA-256 instead. Recorded this "
            "way deliberately: a fabricated run id would have read like a "
            "CI-verifiable provenance that does not exist."
        ),
    }


def default_authorized_note(provenance: dict) -> str:
    """Who authorized THIS run -- never the other path's standing authority.

    The 2026-08-04 operator decision authorized the automated chain. A
    workstation run is not that chain, so it may not inherit its authorization
    line: the note ends up in the artifact's ``reattestationTrigger`` and
    ``limitations``, where it reads as a statement about who sanctioned the
    measurement.
    """
    if provenance["kind"] == LOCAL_SESSION_ORIGIN:
        return (
            "attended local session, run and observed by "
            f"{provenance['operator']}"
        )
    return "automated re-attestation chain, operator-authorized 2026-08-04"


def _report_sha(write_report: dict, path: str) -> str:
    for source in write_report["repositoryExpected"]["sources"]:
        if source["repoRelativePath"] == path:
            return source["sha256"]
    raise ValueError(f"report lists no source entry for {path}")


def _attested_bindings(write_report: dict) -> dict[str, dict[str, str]]:
    bindings: dict[str, dict[str, str]] = {}
    for entry in write_report["repositoryExpected"]["bindings"]:
        if entry["scriptName"] not in (_EVENT_NAME, _EXIT_NAME):
            continue
        producer = entry["expectedProducerName"]
        bindings[entry["scriptName"]] = {
            label: f"{producer}: {label}" for label in entry["labels"]
        }
    if set(bindings) != {_EVENT_NAME, _EXIT_NAME}:
        raise ValueError(
            "report bindings do not cover both attested companions: "
            f"{sorted(bindings)}"
        )
    return bindings


def build_attestation(
    *,
    write_report: dict,
    verify_report: dict,
    prior_evidence: dict,
    prior_evidence_relpath: str,
    event_overlay_text: str,
    exit_signal_text: str,
    provenance: dict,
    write_conclusion: str,
    authorized_note: str,
    source_change_attestation: dict | None = None,
    source_change_attestation_relpath: str | None = None,
) -> dict:
    """Build the new evidence artifact, refusing everything unproven.

    Two sanctioned paths, and nothing else:

    * **pin-only**, proven mechanically by hash reconstruction. No human input.
    * **attested source change**, where ``source_change_attestation`` is a
      checked-in artifact bound by SHA-256 to the sources this generator reads.
      It does not lower the bar; it moves the unprovable part to a named
      observer and keeps every machine-checkable part machine-checked.
    """

    _require(
        provenance.get("kind") in (GITHUB_RUN_ORIGIN, LOCAL_SESSION_ORIGIN),
        f"unknown measurement provenance {provenance.get('kind')!r} -- build it "
        "with github_run_provenance() or local_session_provenance()",
    )
    reference = provenance["reference"]
    workflow = provenance["workflow"]

    # A local session is a narrower provenance than a workflow run, and the
    # artifact has to carry that difference itself -- a reader two supersessions
    # from now has only this file.
    if provenance["kind"] == LOCAL_SESSION_ORIGIN:
        retained = all(
            report["retainedInRepo"] for report in provenance["reports"].values()
        )
        origin_limitations = [
            "The measurement did not come from a workflow run. It was taken in "
            f"an attended session at a workstation by {provenance['operator']}: "
            "there is no GitHub run id to look up and no workflow log holding a "
            "second copy of the reports. The two reports are bound by SHA-256 "
            "in the provenance block and "
            + (
                "are checked in beside this artifact."
                if retained
                else "are NOT checked in, so those digests are re-checkable "
                "only for as long as the local files survive."
            )
        ]
        dispatched_by = (
            f"{provenance['operator']} at a workstation, attended throughout"
        )
    else:
        origin_limitations = []
        dispatched_by = (
            "the automated re-attestation chain (operator-authorized 2026-08-04)"
        )

    _require(
        write_report["executionMode"] == "write",
        f"write report has executionMode {write_report['executionMode']!r}",
    )
    _require(
        verify_report["executionMode"] == "verify-only",
        f"verify report has executionMode {verify_report['executionMode']!r}",
    )

    save = write_report["save"]
    _require(save["failed"] == [], f"save pass reported failures: {save['failed']}")
    _require(
        len(save["succeeded"]) == save["expected"],
        f"save pass completed {len(save['succeeded'])} of {save['expected']}",
    )

    sources = verify_report["sources"]
    _require(sources["drifted"] == 0, f"verify pass found drift: {sources['drifted']}")
    _require(
        sources["checked"] == sources["expected"] and sources["failed"] == [],
        "verify pass did not check every source cleanly",
    )
    bindings_block = verify_report["bindings"]
    _require(
        bindings_block["mismatches"] == 0 and bindings_block["failed"] == [],
        f"verify pass found binding mismatches: {bindings_block['mismatches']}",
    )
    _require(
        verify_report["outOfBandDrift"]["status"] == "clean",
        "out-of-band drift is not clean: "
        f"{verify_report['outOfBandDrift']['status']}",
    )
    _require(
        write_report["repoCommitSha"] == verify_report["repoCommitSha"],
        "write and verify passes ran on different commits",
    )

    overlay_sha = _sha256_text(event_overlay_text)
    exit_sha = _sha256_text(exit_signal_text)
    prior_overlay = prior_evidence["sources"][_EVENT_NAME]
    prior_exit = prior_evidence["sources"][_EXIT_NAME]

    _require(
        _report_sha(write_report, "SMC_Event_Overlay.pine") == overlay_sha
        and _report_sha(write_report, "SMC_Exit_Signal.pine") == exit_sha,
        "report source hashes disagree with the tree this generator reads",
    )
    exit_moved = exit_sha != prior_exit["repositorySha256"]
    _require(
        not exit_moved or source_change_attestation is not None,
        "SMC Exit Signal moved -- the carried replay would describe a source "
        "nobody replayed; this needs a human attestation. Supply one with "
        "--source-change-attestation (gate " + SOURCE_CHANGE_GATE + ").",
    )

    prior_version = int(prior_evidence["libraryReleaseVersion"])
    verdict = classify_event_overlay_change(
        event_overlay_text,
        prior_version=prior_version,
        prior_sha256=prior_overlay["repositorySha256"],
    )
    _require(
        verdict != "identical" or exit_moved,
        "Event Overlay is identical -- nothing to attest",
    )
    _require(
        verdict in ("pin-only", "identical") or source_change_attestation is not None,
        "Event Overlay change is not pin-only -- the automated chain refuses; "
        "record a human attestation instead and pass it with "
        "--source-change-attestation (gate " + SOURCE_CHANGE_GATE + ").",
    )
    attested_change = source_change_attestation is not None
    if attested_change:
        _require(
            source_change_attestation_relpath is not None,
            "an attestation was supplied without the repo-relative path that "
            "the evidence artifact must cite",
        )
        validate_source_change_attestation(
            source_change_attestation, overlay_sha=overlay_sha, exit_sha=exit_sha
        )
    new_version = _pin_version(event_overlay_text)

    compile_mechanism = (
        "saveConsumerSource awaits waitForPostSaveCompileSettlement and then "
        "assertNoVisibleCompileError; the check throws, so it is proven by the "
        f"write pass of {reference} reporting {save['expected']} of "
        f"{save['expected']} saves succeeded rather than recorded as its own "
        "field. The verify-only pass then re-read both sources and resolved "
        "every binding with no runtime error, which is machine evidence that "
        "the saved source loads -- not an attended observation of the compile "
        "badge."
    )

    def _source_block(path: str, sha: str) -> dict[str, Any]:
        return {
            "path": path,
            "repositorySha256": sha,
            "savedSourceReadbackSha256": sha,
            "compileStatus": "passed",
            "compileDiagnostics": [],
            "compileEvidenceMechanism": compile_mechanism,
            "saveRun": reference,
            "savedSourceReadbackRun": reference,
        }

    attested_bindings = _attested_bindings(write_report)
    bindings_checked = sum(len(v) for v in attested_bindings.values())

    if attested_change:
        generator_note = (
            "scripts/smc_r1_generate_attestation.py, which refuses any "
            "attested-source change beyond the import-pin line unless a "
            f"hash-bound {SOURCE_CHANGE_GATE} artifact covers it. One did: "
            f"{source_change_attestation_relpath}."
        )
        diff_character = (
            f"{source_change_attestation['changeCharacter']} Not reconstructible "
            "from the prior bytes, so it is not machine-provable and is carried "
            f"by {source_change_attestation_relpath}, observed by "
            f"{source_change_attestation['observer']} and bound to both source "
            "hashes in this artifact."
        )
        replay_block = {
            "status": "re-run",
            "passedLogicalCases": source_change_attestation["replay"][
                "passedLogicalCases"
            ],
            "evidence": source_change_attestation["replay"]["evidence"],
            "justification": (
                "SMC Exit Signal moved, so the earlier replay could not be "
                "carried over: it would have described a source nobody "
                f"replayed. It was re-run against {exit_sha} and the result is "
                f"attested by {source_change_attestation_relpath}."
            ),
        }
    else:
        generator_note = (
            "scripts/smc_r1_generate_attestation.py, which refuses any "
            "attested-source change beyond the import-pin line."
        )
        diff_character = (
            f"library pin {prior_version} -> {new_version} in the import "
            "line, proven by hash reconstruction; SMC Exit Signal is "
            "byte-identical to the prior attested value and is "
            "re-attested unchanged."
        )
        replay_block = {
            "status": "carried_over",
            "passedLogicalCases": prior_evidence["replay"]["passedLogicalCases"],
            "evidence": prior_evidence["replay"]["evidence"],
            "justification": (
                "The replay evidence covers SMC Exit Signal, whose source "
                "SHA-256 is byte-identical to the prior attested value "
                f"({exit_sha}). The supersession is confined to the Event "
                "Overlay import pin. Nothing the replay measured changed, so "
                "re-running it would produce the same cases against the same "
                "source."
            ),
        }

    return {
        "schemaVersion": 2,
        "capturedAt": verify_report["generatedAt"],
        "scope": (
            "Automated re-attestation of the R1 companion saved sources after "
            f"a library refresh moved the micro-profile release to "
            f"{new_version}. The write and verify passes of {reference} are "
            "the measurement; this artifact records them. Generated by "
            + generator_note
        ),
        "provenance": provenance,
        "supersedes": prior_evidence_relpath,
        "supersessionNote": (
            "The superseded artifact remains checked in and unmodified. It is "
            "a dated measurement of the state on its day and stays true of "
            "that day; it is superseded as the CURRENT attestation, not "
            "corrected. Frozen byte-exact by the evidence chain index."
        ),
        "reattestationTrigger": {
            "reason": (
                "The deliberate re-attestation deferred by "
                "hold_r1_attested_sources: the automated refresh holds the "
                "companions, so their import pin only moves through this "
                f"chain. {authorized_note}."
            ),
            "attestedEventOverlaySha256": prior_overlay["repositorySha256"],
            "supersededByRepositorySha256": overlay_sha,
            "sourceDiffCharacter": diff_character,
        },
        "authorization": {
            "account": "preuss_steffen",
            "layout": "SMC Simple Management R1",
            "visibility": "private",
            "publicationAuthorized": False,
            "alertMutationAuthorized": False,
            "railwayMutationAuthorized": False,
        },
        "sources": {
            _EVENT_NAME: _source_block("SMC_Event_Overlay.pine", overlay_sha),
            _EXIT_NAME: _source_block("SMC_Exit_Signal.pine", exit_sha),
        },
        "tradingView": {
            "account": "preuss_steffen",
            "layout": "SMC Simple Management R1",
            "layoutUrl": prior_evidence.get("tradingView", {}).get("layoutUrl", ""),
            "consumersFoundOnChart": [_EVENT_NAME, _EXIT_NAME],
            "bindings": attested_bindings,
            "bindingsChecked": bindings_checked,
            "bindingMismatches": bindings_block["mismatches"],
            "bindingStatusAfterChartLoad": "passed",
            "bindingObservationCount": 2,
            "chartRuntimeErrorsAfterLoad": [],
            "unknownParentRuntimeError": False,
            "suitePresence": "inferred",
            "suitePresenceEvidence": (
                "Every BUS input resolved to its expected producer parent with "
                "zero unknown-parent runtime errors in the verify pass. No "
                "direct chart-inventory scan of the producer was run, so the "
                "Suite's presence is inferred from live parent resolution "
                "rather than counted."
            ),
            "alertsCreated": False,
            "alertsModified": False,
            "alertMutationEvidence": (
                "None of the executed scripts (tv_batch_consumer_rollout.ts, "
                "tv_save_consumer_source.ts, tv_verify_consumer_bindings.ts) "
                "contains any alert creation, modification, or removal path."
            ),
            "compileStatusAfterFinalReload": "not_run",
            "alertConditionInventory": "not_run",
            "holdManagerPresent": "not_run",
            "forbiddenConcurrentScriptsPresent": "not_run",
            "finalInventory": "not_run",
            "layoutSaveStatus": (
                "performed" if write_report["mutations"]["layoutSaved"] else "not_required"
            ),
            "layoutSaveNote": (
                f"The write pass of {reference} saved the consumer sources "
                "and the layout; the verify-only pass then re-read the result "
                "with zero drift and zero binding mismatches."
            ),
            "outOfBandDrift": verify_report["outOfBandDrift"]["status"],
            "observedBy": f"{reference}, executionMode verify-only",
        },
        "rollback": {
            "status": "carried_over",
            "evidence": prior_evidence["rollback"]["evidence"],
            "justification": (
                "The companion rollback drill's own dated artifact carries it. "
                "It was NOT re-run by this attestation. What happened instead "
                "is narrower and machine-observed: the write pass re-saved the "
                "companion sources and the verify pass found every binding "
                "correct with no unknown-parent runtime error. That exercises "
                "re-binding after a save; it is not the drill's controlled "
                "remove / reload / verify-Suite-only / restore sequence, and "
                "it is not recorded as one."
            ),
        },
        "replay": replay_block,
        "openGates": list(prior_evidence["openGates"]),
        "limitations": [
            "No TradingView alert was created, changed, enabled, or disabled.",
            "No script was published.",
            "No Railway service, variable, deployment, or secret was changed.",
            (
                f"Generated mechanically from the write and verify passes of "
                f"{reference} by scripts/smc_r1_generate_attestation.py; "
                f"{authorized_note}."
            ),
            *origin_limitations,
            (
                "This artifact re-attests SOURCES and bindings. The attended "
                "gates listed under openGates were NOT re-measured; they are "
                "carried exactly as on the superseded artifact."
            ),
            (
                "The dated artifacts that close those gates were observed "
                "against a superseded source. A library-pin bump is not known "
                "to change an alert condition, a layout inventory, or the "
                "rollback sequence, but that is reasoning, not a new "
                "measurement, and it is recorded here as such."
            ),
            (
                "The producer's presence on the R1 layout is inferred from "
                "resolved BUS parents, not counted by an inventory scan."
            ),
        ],
        "evidenceRuns": [
            {
                "origin": reference,
                "workflow": workflow,
                "executionMode": "write",
                "capturedAt": write_report["generatedAt"],
                "contributes": (
                    f"{save['expected']} of {save['expected']} consumer sources "
                    "saved, bindings repaired, layout saved"
                ),
                "dispatchedBy": dispatched_by,
                "conclusion": write_conclusion,
            },
            {
                "origin": reference,
                "workflow": workflow,
                "executionMode": "verify-only",
                "capturedAt": verify_report["generatedAt"],
                "contributes": (
                    f"independent read-back: {sources['checked']} of "
                    f"{sources['expected']} sources checked and 0 drifted, "
                    f"{bindings_block['checkedBindings']} bindings checked and "
                    "0 mismatches, out-of-band drift clean"
                ),
                "dispatchedBy": dispatched_by,
            },
        ],
        "repoCommitSha": write_report["repoCommitSha"],
        "libraryReleaseVersion": new_version,
    }


def evidence_filename(captured_at: str) -> str:
    """Timestamped, collision-free within a day, glob-compatible with the chain."""
    match = re.match(r"^(\d{4}-\d{2}-\d{2})T(\d{2}):(\d{2}):(\d{2})", captured_at)
    if match is None:
        raise ValueError(f"unparseable capturedAt: {captured_at!r}")
    date, hh, mm, ss = match.groups()
    return f"smc_r1_live_rollout_evidence_{date}T{hh}{mm}{ss}Z.json"


def write_attestation(evidence: dict, repo_root: Path) -> Path:
    out = (
        repo_root
        / "artifacts"
        / "governance"
        / evidence_filename(evidence["capturedAt"])
    )
    atomic_write_text(json.dumps(evidence, indent=2) + "\n", out)
    return out


def append_chain(
    index_path: Path, evidence_path: Path, evidence: dict, *, repo_root: Path
) -> None:
    """Append the new artifact to the supersession chain, order-checked."""
    payload = json.loads(index_path.read_text(encoding="utf-8"))
    head = payload["chain"][-1]
    _require(
        evidence["supersedes"] == head["path"],
        "evidence supersedes "
        f"{evidence['supersedes']!r} but the chain head is {head['path']!r} -- "
        "appending would orphan a reading",
    )
    _require(
        evidence["capturedAt"] > head["capturedAt"],
        "evidence capture time does not advance past the chain head",
    )
    payload["chain"].append(
        {
            "path": evidence_path.relative_to(repo_root).as_posix(),
            "capturedAt": evidence["capturedAt"],
            "sha256": hashlib.sha256(evidence_path.read_bytes()).hexdigest(),
        }
    )
    atomic_write_text(json.dumps(payload, indent=2) + "\n", index_path)


def verify_chain(index_path: Path, *, repo_root: Path) -> None:
    """Re-prove the chain invariants, stdlib-only, before anything is committed.

    A ``bot/r1-reattest`` PR is data-only for fast-gates, so the heavy suite
    (and with it tests/test_smc_r1_evidence_chain.py) first runs on main AFTER
    the merge. This is the same set of invariants, run inside the workflow run
    that just extended the chain -- fail-closed while the evidence commit can
    still simply not happen.
    """
    payload = json.loads(index_path.read_text(encoding="utf-8"))
    chain = payload["chain"]
    _require(len(chain) >= 2, "chain needs at least a head and its predecessor")
    previous_entry: dict | None = None
    for entry in chain:
        artifact_path = repo_root / entry["path"]
        _require(artifact_path.is_file(), f"chain names a missing artifact: {entry['path']}")
        digest = hashlib.sha256(artifact_path.read_bytes()).hexdigest()
        _require(
            digest == entry["sha256"],
            f"{entry['path']} no longer matches its registered SHA-256 -- a "
            "dated measurement was rewritten",
        )
        artifact = json.loads(artifact_path.read_text(encoding="utf-8"))
        _require(
            artifact["capturedAt"] == entry["capturedAt"],
            f"{entry['path']} capture time disagrees with its chain entry",
        )
        if previous_entry is not None:
            _require(
                artifact.get("supersedes") == previous_entry["path"],
                f"{entry['path']} does not supersede the previous chain entry",
            )
            _require(
                entry["capturedAt"] > previous_entry["capturedAt"],
                "chain capture times do not strictly increase",
            )
        previous_entry = entry


def main() -> int:
    # Imported here so the module surface above stays import-light for tests;
    # main() is the only consumer of the repository-bound constants.
    from scripts.smc_r1_rollout_contract import (
        EVENT_SOURCE,
        EVIDENCE_CHAIN_INDEX,
        EXIT_SOURCE,
        ROOT,
        load_evidence_chain,
    )

    parser = argparse.ArgumentParser()
    parser.add_argument("--write-report", type=Path, required=True)
    parser.add_argument("--verify-report", type=Path, required=True)
    parser.add_argument(
        "--run-id",
        type=int,
        default=None,
        help=(
            "GitHub Actions run id of the workflow run that produced both "
            "reports. Exactly one of --run-id / --local-session-operator."
        ),
    )
    parser.add_argument(
        "--local-session-operator",
        default=None,
        help=(
            "Name of the operator who ran the measurement at a workstation, "
            "for a session that has no GitHub run id. The reports are bound to "
            "the artifact by SHA-256 instead of by run."
        ),
    )
    parser.add_argument("--workflow", default="tv-save-consumer-source")
    parser.add_argument(
        "--write-conclusion",
        default="failure - at the un-attested-save guard, after the saves completed",
    )
    parser.add_argument(
        "--authorized-note",
        default=None,
        help=(
            "Who authorized this re-attestation. Defaults to the standing "
            "2026-08-04 authorization for the automated chain; a local session "
            "defaults to its own operator instead, because the chain's "
            "authorization does not cover a workstation run."
        ),
    )
    parser.add_argument(
        "--source-change-attestation",
        type=Path,
        default=None,
        help=(
            "Repo-relative path to a checked-in "
            f"{SOURCE_CHANGE_GATE} artifact. Required when an attested source "
            "changes beyond its import-pin line; refused when it does not "
            "match the source hashes this generator reads."
        ),
    )
    args = parser.parse_args()

    if (args.run_id is None) == (args.local_session_operator is None):
        parser.error(
            "name the measurement's origin exactly once: --run-id <n> for a "
            "workflow run, or --local-session-operator <name> for an attended "
            "session at a workstation. Passing neither leaves the artifact "
            "unable to say where its measurement came from; passing both makes "
            "it say two different things."
        )
    if args.run_id is not None:
        provenance = github_run_provenance(args.run_id, workflow=args.workflow)
    else:
        provenance = local_session_provenance(
            operator=args.local_session_operator,
            workflow=args.workflow,
            write_report_path=args.write_report,
            verify_report_path=args.verify_report,
            repo_root=ROOT,
        )
    authorized_note = args.authorized_note or default_authorized_note(provenance)

    attestation = None
    attestation_relpath = None
    if args.source_change_attestation is not None:
        attestation_path = args.source_change_attestation
        attestation = json.loads(attestation_path.read_text(encoding="utf-8"))
        attestation_relpath = str(
            attestation_path.resolve().relative_to(ROOT)
            if attestation_path.is_absolute()
            else attestation_path
        )

    chain = load_evidence_chain()
    prior_relpath = chain[-1]["path"]
    prior_evidence = json.loads((ROOT / prior_relpath).read_text(encoding="utf-8"))

    evidence = build_attestation(
        write_report=json.loads(args.write_report.read_text(encoding="utf-8")),
        verify_report=json.loads(args.verify_report.read_text(encoding="utf-8")),
        prior_evidence=prior_evidence,
        prior_evidence_relpath=prior_relpath,
        event_overlay_text=EVENT_SOURCE.read_text(encoding="utf-8"),
        exit_signal_text=EXIT_SOURCE.read_text(encoding="utf-8"),
        provenance=provenance,
        write_conclusion=args.write_conclusion,
        authorized_note=authorized_note,
        source_change_attestation=attestation,
        source_change_attestation_relpath=attestation_relpath,
    )
    out = write_attestation(evidence, ROOT)
    append_chain(EVIDENCE_CHAIN_INDEX, out, evidence, repo_root=ROOT)
    verify_chain(EVIDENCE_CHAIN_INDEX, repo_root=ROOT)
    print(out.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
