#!/usr/bin/env -S node --enable-source-maps

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  assertNoVisibleCompileError,
  closeTradingViewSession,
  collectOpenScriptIdentityTexts,
  ensurePineEditor,
  detectPineCompileErrorMarker,
  gotoChart,
  newTradingViewSession,
  openExistingScript,
  openFreshUntitledPineDraft,
  publishPrivateScript,
  resolveOpenScriptIdentityEvidence,
  saveScript,
  setEditorContent,
  takeScreenshot,
  utcNow,
  waitForPostSaveCompileSettlement,
  writeJson,
} from "../automation/tradingview/lib/tv_shared.js";

// Open-Prep daily panel publisher.
//
// Publishes pine/generated/openprep_daily_panel.pine (generated by
// scripts/generate_openprep_pine_panel.py) as a private TradingView
// **indicator**. The publish flow mirrors tv_publish_overlay_library.ts, with
// two deliberate simplifications because the panel is an indicator, not a
// versioned library:
//   * the contract check only asserts the source exists and carries the
//     expected `indicator("<scriptName>"` header (no manifest / import-path /
//     alias / library version), and
//   * verification is **identity-only** (`script_context`). A daily-republished
//     indicator has no library "version N" string, so the library publishers'
//     version gate does not apply; success is: no visible compile error, the
//     publish dialog completed, and the live script re-opens under the same name.
//
// CI-only: node/npm are not part of the local toolchain, so this file is
// exercised in the TradingView publish workflow (its pure contract check is
// unit-tested in automation/tradingview/tests/).

type IdentityVerificationMode = "script_context" | "not_verified";
type OpenMode = "existing" | "fresh_draft";

type CliArgs = {
  panel: string;
  scriptName: string;
  description: string;
  out: string;
  openExisting: boolean;
  allowCreate: boolean;
};

type ContractDetails = {
  panelPath: string;
  scriptName: string;
};

type PublishPanelReport = {
  generatedAt: string;
  ok: boolean;
  contractOk: boolean;
  publishAttempted: boolean;
  publishOk: boolean;
  openMode: OpenMode;
  openExistingRequested: boolean;
  openedExistingScript: boolean;
  createdFreshDraft: boolean;
  publishedScriptVerified: boolean;
  identityVerificationMode: IdentityVerificationMode;
  scriptName: string;
  noChangeDetected: boolean;
  identityEvidenceContext: string[];
  publishBodyText: string;
  screenshots: string[];
  error?: string;
};

const DEFAULT_SCRIPT_NAME = "Open-Prep Daily Panel";
const DEFAULT_PANEL = "pine/generated/openprep_daily_panel.pine";

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);

  function getFlag(name: string, fallback: string): string {
    const index = args.indexOf(name);
    if (index === -1 || !args[index + 1]) {
      return fallback;
    }
    return args[index + 1];
  }

  function hasFlag(name: string): boolean {
    return args.includes(name);
  }

  return {
    panel: path.resolve(getFlag("--panel", DEFAULT_PANEL)),
    scriptName: getFlag("--script-name", DEFAULT_SCRIPT_NAME),
    description: getFlag(
      "--description",
      "Open-Prep daily watchlist + market-weather panel. Auto-generated; observe-only (does not drive scoring or playbook selection).",
    ),
    out: path.resolve(
      getFlag(
        "--out",
        `automation/tradingview/reports/publish-openprep-panel-${utcNow().replace(/[:.]/g, "-")}.json`,
      ),
    ),
    openExisting: hasFlag("--no-open-existing") ? false : true,
    allowCreate: hasFlag("--no-allow-create") ? false : true,
  };
}

// Narrow input so the contract can be unit-tested without a full CliArgs.
export type PanelContractInput = Pick<CliArgs, "panel" | "scriptName">;

export function verifyPanelPublishContract(cli: PanelContractInput): ContractDetails {
  if (!fs.existsSync(cli.panel)) {
    throw new Error(`Missing Open-Prep panel source: ${cli.panel}`);
  }

  const panelText = fs.readFileSync(cli.panel, "utf-8");
  const expectedHeader = `indicator("${cli.scriptName}"`;
  if (!panelText.includes(expectedHeader)) {
    throw new Error(`Open-Prep panel header mismatch: expected ${expectedHeader}`);
  }
  if (!panelText.includes("//@version=6")) {
    throw new Error("Open-Prep panel must declare //@version=6");
  }

  return {
    panelPath: cli.panel,
    scriptName: cli.scriptName,
  };
}

export async function runPublishOpenPrepPanelCli(): Promise<number> {
  const cli = parseArgs();
  const runId = utcNow().replace(/[:.]/g, "-");
  const screenshots: string[] = [];
  let details: ContractDetails | null = null;
  let publishAttempted = false;
  let openMode: OpenMode = "fresh_draft";
  let openedExistingScript = false;
  let createdFreshDraft = false;
  let publishedScriptVerified = false;
  let identityVerificationMode: IdentityVerificationMode = "not_verified";
  let noChangeDetected = false;
  let identityEvidenceContext: string[] = [];
  let publishBodyText = "";

  try {
    if (!cli.openExisting && !cli.allowCreate) {
      throw new Error(
        "--no-open-existing combined with --no-allow-create cannot publish: it would neither update the existing script nor be allowed to create one.",
      );
    }
    details = verifyPanelPublishContract(cli);
    const session = await newTradingViewSession();
    try {
      if (!session.authResolution.authReusedOk) {
        throw new Error(
          "TradingView Open-Prep panel publish requires a reusable authenticated session. Refresh TV_STORAGE_STATE or TV_PERSISTENT_PROFILE_DIR first.",
        );
      }

      await gotoChart(session.page);
      await ensurePineEditor(session.page);

      if (cli.openExisting) {
        openedExistingScript = await openExistingScript(session.page, details.scriptName).catch(() => false);
        if (openedExistingScript) {
          openMode = "existing";
        } else if (!cli.allowCreate) {
          throw new Error(`Could not open existing TradingView script: ${details.scriptName}`);
        } else {
          await openFreshUntitledPineDraft(session.page, "indicator");
          createdFreshDraft = true;
          openMode = "fresh_draft";
        }
      } else {
        await openFreshUntitledPineDraft(session.page, "indicator");
        createdFreshDraft = true;
        openMode = "fresh_draft";
      }

      const code = fs.readFileSync(details.panelPath, "utf-8");
      await setEditorContent(session.page, code);
      await saveScript(session.page, details.scriptName);
      await waitForPostSaveCompileSettlement(session.page, details.scriptName);
      await assertNoVisibleCompileError(session.page);
      await takeScreenshot(session.page, runId, `${details.scriptName}-compiled`, screenshots);

      publishAttempted = true;
      let publishResult: Awaited<ReturnType<typeof publishPrivateScript>>;
      try {
        publishResult = await publishPrivateScript(session.page, {
          scriptName: details.scriptName,
          title: details.scriptName,
          description: cli.description,
          requireCleanChartBeforePublish: true,
        });
      } catch (publishError) {
        await takeScreenshot(
          session.page, runId, `${details.scriptName}-publish-failed`, screenshots,
        ).catch(() => "");
        throw publishError;
      }
      noChangeDetected = publishResult.noChangeDetected;
      publishBodyText = publishResult.bodyText;
      const publishCompileError = detectPineCompileErrorMarker(publishBodyText);
      if (publishCompileError) {
        throw new Error(
          `TradingView publish evidence contains a Pine compiler error for ${details.scriptName}: ${publishCompileError}`,
        );
      }
      await takeScreenshot(session.page, runId, `${details.scriptName}-published`, screenshots);

      // Identity-only verification (indicator has no library version).
      identityEvidenceContext = await collectOpenScriptIdentityTexts(session.page, details.scriptName).catch(() => []);
      let bodyText = publishResult.bodyText || (await session.page.locator("body").innerText().catch(() => ""));
      let identityEvidence = resolveOpenScriptIdentityEvidence(details.scriptName, {
        dialogStillVisible: false,
        editorContextTexts: identityEvidenceContext,
      });
      identityVerificationMode = identityEvidence.verificationMode;

      // Fallback: re-open the live script by name and re-check identity.
      if (identityVerificationMode !== "script_context") {
        publishedScriptVerified = await openExistingScript(session.page, details.scriptName).catch(() => false);
        identityEvidenceContext = await collectOpenScriptIdentityTexts(session.page, details.scriptName).catch(() => []);
        bodyText = await session.page.locator("body").innerText().catch(() => "");
        identityEvidence = resolveOpenScriptIdentityEvidence(details.scriptName, {
          dialogStillVisible: false,
          editorContextTexts: identityEvidenceContext,
        });
        identityVerificationMode = identityEvidence.verificationMode;
      }

      const exactScriptVerified = publishedScriptVerified || identityVerificationMode === "script_context";
      if (!exactScriptVerified) {
        throw new Error(
          `Published TradingView Open-Prep panel could not be verified by identity: live_script_verified=${publishedScriptVerified}, identity_mode=${identityVerificationMode}, no_change_detected=${noChangeDetected}`,
        );
      }
      publishedScriptVerified = exactScriptVerified;
    } finally {
      await closeTradingViewSession(session);
    }

    const report: PublishPanelReport = {
      generatedAt: utcNow(),
      ok: true,
      contractOk: true,
      publishAttempted,
      publishOk: true,
      openMode,
      openExistingRequested: cli.openExisting,
      openedExistingScript,
      createdFreshDraft,
      publishedScriptVerified,
      identityVerificationMode,
      scriptName: details.scriptName,
      noChangeDetected,
      identityEvidenceContext,
      publishBodyText,
      screenshots,
    };
    writeJson(cli.out, report);
    process.stdout.write(JSON.stringify(report, null, 2));
    process.stdout.write("\n");
    return 0;
  } catch (error: unknown) {
    const message = error instanceof Error ? error.stack || error.message : String(error);
    const report: PublishPanelReport = {
      generatedAt: utcNow(),
      ok: false,
      contractOk: details !== null,
      publishAttempted,
      publishOk: false,
      openMode,
      openExistingRequested: cli.openExisting,
      openedExistingScript,
      createdFreshDraft,
      publishedScriptVerified,
      identityVerificationMode,
      scriptName: details?.scriptName ?? cli.scriptName,
      noChangeDetected,
      identityEvidenceContext,
      publishBodyText,
      screenshots,
      error: message,
    };
    writeJson(cli.out, report);
    process.stdout.write(JSON.stringify(report, null, 2));
    process.stdout.write("\n");
    return 1;
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  runPublishOpenPrepPanelCli()
    .then((code) => process.exit(code))
    .catch((error: unknown) => {
      console.error(error instanceof Error ? error.stack || error.message : String(error));
      process.exit(1);
    });
}
